In [1]:
S1_G=[6, 5.1, 4, 3.1, 2, 1.1 ]
S1_D=[0,3.01]
S2_G=[18, 15.01, 12,9.01,6,3.01]
S2_D=[0,9.001]

T_G=[round(x+y,3) for x in S1_G for y in S2_G]
T_D=[round(x+y,3) for x in S1_D for y in S2_D]

G_D=[round(x+y,3) for x in S1_G for y in S2_D]

PAV= T_G+G_D+T_D
PAV.sort()

print(T_G)
print(T_D)
print(G_D)

print(PAV)

[24, 21.01, 18, 15.01, 12, 9.01, 23.1, 20.11, 17.1, 14.11, 11.1, 8.11, 22, 19.01, 16, 13.01, 10, 7.01, 21.1, 18.11, 15.1, 12.11, 9.1, 6.11, 20, 17.01, 14, 11.01, 8, 5.01, 19.1, 16.11, 13.1, 10.11, 7.1, 4.11]
[0, 9.001, 3.01, 12.011]
[6, 15.001, 5.1, 14.101, 4, 13.001, 3.1, 12.101, 2, 11.001, 1.1, 10.101]
[0, 1.1, 2, 3.01, 3.1, 4, 4.11, 5.01, 5.1, 6, 6.11, 7.01, 7.1, 8, 8.11, 9.001, 9.01, 9.1, 10, 10.101, 10.11, 11.001, 11.01, 11.1, 12, 12.011, 12.101, 12.11, 13.001, 13.01, 13.1, 14, 14.101, 14.11, 15.001, 15.01, 15.1, 16, 16.11, 17.01, 17.1, 18, 18.11, 19.01, 19.1, 20, 20.11, 21.01, 21.1, 22, 23.1, 24]


In [14]:
b=2
b

2

In [2]:
#Sommet2, tout gauche
TG2= [round( int(x)-4  +  (abs((int(10*x)%10 - 1))%2)*0.1  
            +  (abs((int(100*x)%10 - 1))%2)*0.01 + (abs((int(1000*x)%10))%2)*0.001,3) for x in T_G]
print(TG2)
presentTG2=[  x in PAV for x in TG2]
print(presentTG2)

[20.11, 17.1, 14.11, 11.1, 8.11, 5.1, 19.01, 16.0, 13.01, 10.0, 7.01, 4.001, 18.11, 15.1, 12.11, 9.1, 6.11, 3.1, 17.01, 14.0, 11.01, 8.0, 5.01, 2.0, 16.11, 13.1, 10.11, 7.1, 4.11, 1.1, 15.01, 12.0, 9.01, 6.0, 3.01, 0.0]
[True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]


In [3]:
#Sommet1, tout gauche
TG1= [round( int(x)-1  +  (abs((int(10*x)%10 - 1))%2)*0.1  
            +  (abs((int(100*x)%10))%2)*0.01 + (abs((int(1000*x)%10))%2)*0.001 ,3) for x in T_G]
print(TG1)
presentTG1=[  x in PAV for x in TG1]
print(presentTG1)

[23.1, 20.11, 17.1, 14.11, 11.1, 8.11, 22.0, 19.01, 16.0, 13.01, 10.0, 7.011, 21.1, 18.11, 15.1, 12.11, 9.1, 6.11, 20.0, 17.01, 14.0, 11.01, 8.0, 5.01, 19.1, 16.11, 13.1, 10.11, 7.1, 4.11, 18.0, 15.01, 12.0, 9.01, 6.0, 3.01]
[True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]


In [4]:
#Sommet1, gauche droite
GD1=[round( int(x)-1  +  (abs((int(10*x)%10 - 1))%2)*0.1  
           +  (abs((int(100*x)%10))%2)*0.01 + (abs((int(1000*x)%10))%2)*0.001 ,3) for x in G_D]
print(G_D)
print(GD1)
presentGD1=[  x in PAV for x in GD1]
print(presentGD1)

[6, 15.001, 5.1, 14.101, 4, 13.001, 3.1, 12.101, 2, 11.001, 1.1, 10.101]
[5.1, 14.101, 4.01, 13.001, 3.1, 12.101, 2.0, 11.001, 1.1, 10.101, 0.0, 9.001]
[True, True, False, True, True, True, True, True, True, True, True, True]


In [5]:
#Sommet2, gauche droite
GD2= [round( int(x)-4  +  (abs((int(10*x)%10 - 1))%2)*0.1  
            +  (abs((int(100*x)%10 - 1))%2)*0.01 +(abs((int(1000*x)%10))%2)*0.001 ,3) for x in G_D]
print(G_D)
print(GD2)
presentGD2=[  x in PAV for x in GD2]
print(presentGD2)

[6, 15.001, 5.1, 14.101, 4, 13.001, 3.1, 12.101, 2, 11.001, 1.1, 10.101]
[2.11, 11.111, 1.0, 10.011, 0.11, 9.111, -0.99, 8.011, -1.89, 7.111, -2.99, 6.011]
[False, False, False, False, False, False, False, False, False, False, False, False]


In [6]:
GD22= [round( int(x)+13  +  (abs((int(10*x)%10 + 1))%2)*0.1  
            +  (abs((int(100*x)%10 + 1))%2)*0.01 +(abs((int(1000*x)%10 +1))%2)*0.001 ,3) for x in GD2]
print(GD22)
presentGD22=[  x in PAV for x in GD22]
print(presentGD22)

[15.001, 24.0, 14.111, 23.1, 13.001, 22.0, 13.001, 21.101, 12.101, 20.0, 11.001, 19.1]
[True, True, False, True, True, True, True, False, True, True, True, True]


In [7]:
#Sommet1, tout droite
TD1=[round( int(x)-1  +  (abs((int(10*x)%10 - 1))%2)*0.1  
           +  (abs((int(100*x)%10))%2)*0.01 + (abs((int(1000*x)%10))%2)*0.001 ,3) for x in T_D]
print(T_D)
print(TD1)
presentTD1=[  x in PAV for x in TD1]
print(presentTD1)

TD12= [round( int(x)+13  +  (abs((int(10*x)%10 + 1))%2)*0.1  
            +  (abs((int(100*x)%10 + 1))%2)*0.01 +(abs((int(1000*x)%10 +1))%2)*0.001 ,3) for x in TD1]
print(TD12)
presentTD12=[  x in PAV for x in TD12]
print(presentTD12)

[0, 9.001, 3.01, 12.011]
[-0.9, 8.101, 2.11, 11.111]
[False, False, False, False]
[13.011, 21.01, 15.001, 24.0]
[False, True, True, True]


In [8]:
#Sommet2, tout droite
TD2= [round( int(x)-4  +  (abs((int(10*x)%10 - 1))%2)*0.1  
            +  (abs((int(100*x)%10 - 1))%2)*0.01 + (abs((int(1000*x)%10))%2)*0.001,3) for x in T_D]
print(TD2)
presentTD2=[  x in PAV for x in TD2]
print(presentTD2)

TD22= [round( int(x)+13  +  (abs((int(10*x)%10 + 1))%2)*0.1  
            +  (abs((int(100*x)%10 + 1))%2)*0.01 +(abs((int(1000*x)%10 +1))%2)*0.001 ,3) for x in TD2]
print(TD22)
presentTD22=[  x in PAV for x in TD22]
print(presentTD22)

[-3.89, 5.111, -0.9, 8.101]
[False, False, False, False]
[10.101, 18.0, 13.011, 21.01]
[True, True, False, True]


In [9]:
import numpy as np
v1= [np.array([0,0]), np.array([3,1]), np.array([3,-1]), np.array([2,-1]) ]
v2= [np.array([0,0]), np.array([3,3]), np.array([3,5]), np.array([2,7]) ]
v3= [np.array([0,0]), np.array([4,1]), np.array([5,1]), np.array([6,-1]) ]

for x in v1:
    for y in v2:
        for z in v3:
            print(x,"+",y,"+",z,"=",np.array([(x[0]+y[0]+z[0]),(x[1]+y[1]+z[1]) ]))




[0 0] + [0 0] + [0 0] = [0 0]
[0 0] + [0 0] + [4 1] = [4 1]
[0 0] + [0 0] + [5 1] = [5 1]
[0 0] + [0 0] + [ 6 -1] = [ 6 -1]
[0 0] + [3 3] + [0 0] = [3 3]
[0 0] + [3 3] + [4 1] = [7 4]
[0 0] + [3 3] + [5 1] = [8 4]
[0 0] + [3 3] + [ 6 -1] = [9 2]
[0 0] + [3 5] + [0 0] = [3 5]
[0 0] + [3 5] + [4 1] = [7 6]
[0 0] + [3 5] + [5 1] = [8 6]
[0 0] + [3 5] + [ 6 -1] = [9 4]
[0 0] + [2 7] + [0 0] = [2 7]
[0 0] + [2 7] + [4 1] = [6 8]
[0 0] + [2 7] + [5 1] = [7 8]
[0 0] + [2 7] + [ 6 -1] = [8 6]
[3 1] + [0 0] + [0 0] = [3 1]
[3 1] + [0 0] + [4 1] = [7 2]
[3 1] + [0 0] + [5 1] = [8 2]
[3 1] + [0 0] + [ 6 -1] = [9 0]
[3 1] + [3 3] + [0 0] = [6 4]
[3 1] + [3 3] + [4 1] = [10  5]
[3 1] + [3 3] + [5 1] = [11  5]
[3 1] + [3 3] + [ 6 -1] = [12  3]
[3 1] + [3 5] + [0 0] = [6 6]
[3 1] + [3 5] + [4 1] = [10  7]
[3 1] + [3 5] + [5 1] = [11  7]
[3 1] + [3 5] + [ 6 -1] = [12  5]
[3 1] + [2 7] + [0 0] = [5 8]
[3 1] + [2 7] + [4 1] = [9 9]
[3 1] + [2 7] + [5 1] = [10  9]
[3 1] + [2 7] + [ 6 -1] = [11  7]
[ 3 -1

In [10]:
PAV= [np.array([(x[0]+y[0]+z[0]),(x[1]+y[1]+z[1]) ])     for x in v1 for y in v2 for z in v3]
print(PAV)

ensemble_unique = set(map(tuple, PAV))

# Convertir chaque tuple unique en np.array
pav = [np.array(x) for x in ensemble_unique]

print(pav)

print(len(PAV))
print(len(pav))
matrice=np.stack(pav)
print(matrice)

[array([0, 0]), array([4, 1]), array([5, 1]), array([ 6, -1]), array([3, 3]), array([7, 4]), array([8, 4]), array([9, 2]), array([3, 5]), array([7, 6]), array([8, 6]), array([9, 4]), array([2, 7]), array([6, 8]), array([7, 8]), array([8, 6]), array([3, 1]), array([7, 2]), array([8, 2]), array([9, 0]), array([6, 4]), array([10,  5]), array([11,  5]), array([12,  3]), array([6, 6]), array([10,  7]), array([11,  7]), array([12,  5]), array([5, 8]), array([9, 9]), array([10,  9]), array([11,  7]), array([ 3, -1]), array([7, 0]), array([8, 0]), array([ 9, -2]), array([6, 2]), array([10,  3]), array([11,  3]), array([12,  1]), array([6, 4]), array([10,  5]), array([11,  5]), array([12,  3]), array([5, 6]), array([9, 7]), array([10,  7]), array([11,  5]), array([ 2, -1]), array([6, 0]), array([7, 0]), array([ 8, -2]), array([5, 2]), array([9, 3]), array([10,  3]), array([11,  1]), array([5, 4]), array([9, 5]), array([10,  5]), array([11,  3]), array([4, 6]), array([8, 7]), array([9, 7]), arra

In [11]:
print(set(matrice[:,0]))

print(set(matrice[:,1]))

np_array_recherche = np.array([7,8])
presence = any(np.array_equal(np_array_recherche, array) for array in pav)
print(presence)

{0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, -2, -1}
True


In [13]:
import numpy as np
v1= [np.array([0,0,0]), np.array([1,2,3]), np.array([1,2,2]), np.array([1,1,1]) ]
v2= [np.array([0,0,0]), np.array([1,2,4]), np.array([1,2,0]), np.array([1,1,0]) ]
v3= [np.array([0,0,0]), np.array([1,3,4]), np.array([1,4,0]), np.array([1,0,0]) ]

for x in v1:
    for y in v2:
        for z in v3:
            print(x,"+",y,"+",z,"=",np.array([(x[0]+y[0]+z[0]),(x[1]+y[1]+z[1])%5, (x[2]+y[2]+z[2])%5 ]))




[0 0 0] + [0 0 0] + [0 0 0] = [0 0 0]
[0 0 0] + [0 0 0] + [1 3 4] = [1 3 4]
[0 0 0] + [0 0 0] + [1 4 0] = [1 4 0]
[0 0 0] + [0 0 0] + [1 0 0] = [1 0 0]
[0 0 0] + [1 2 4] + [0 0 0] = [1 2 4]
[0 0 0] + [1 2 4] + [1 3 4] = [2 0 3]
[0 0 0] + [1 2 4] + [1 4 0] = [2 1 4]
[0 0 0] + [1 2 4] + [1 0 0] = [2 2 4]
[0 0 0] + [1 2 0] + [0 0 0] = [1 2 0]
[0 0 0] + [1 2 0] + [1 3 4] = [2 0 4]
[0 0 0] + [1 2 0] + [1 4 0] = [2 1 0]
[0 0 0] + [1 2 0] + [1 0 0] = [2 2 0]
[0 0 0] + [1 1 0] + [0 0 0] = [1 1 0]
[0 0 0] + [1 1 0] + [1 3 4] = [2 4 4]
[0 0 0] + [1 1 0] + [1 4 0] = [2 0 0]
[0 0 0] + [1 1 0] + [1 0 0] = [2 1 0]
[1 2 3] + [0 0 0] + [0 0 0] = [1 2 3]
[1 2 3] + [0 0 0] + [1 3 4] = [2 0 2]
[1 2 3] + [0 0 0] + [1 4 0] = [2 1 3]
[1 2 3] + [0 0 0] + [1 0 0] = [2 2 3]
[1 2 3] + [1 2 4] + [0 0 0] = [2 4 2]
[1 2 3] + [1 2 4] + [1 3 4] = [3 2 1]
[1 2 3] + [1 2 4] + [1 4 0] = [3 3 2]
[1 2 3] + [1 2 4] + [1 0 0] = [3 4 2]
[1 2 3] + [1 2 0] + [0 0 0] = [2 4 3]
[1 2 3] + [1 2 0] + [1 3 4] = [3 2 2]
[1 2 3] + [1

In [15]:
PAV= [np.array([(x[0]+y[0]+z[0]),(x[1]+y[1]+z[1])%5, (x[2]+y[2]+z[2])%5 ])   for x in v1 for y in v2 for z in v3]
#print(PAV)

ensemble_unique = set(map(tuple, PAV))

# Convertir chaque tuple unique en np.array
pav = [np.array(x) for x in ensemble_unique]

#print(pav)

#print(len(PAV))
#print(len(pav))
matrice=np.stack(pav)
#print(matrice)
matrice1= []
for i in range(4):
    matrice1.append([])

for element in matrice:
    matrice1[element[0]].append(element)

for element in matrice1:
    truc = np.stack(element)
    print(len(truc))
    print(truc)
    print()

1
[[0 0 0]]

9
[[1 2 2]
 [1 1 0]
 [1 2 4]
 [1 0 0]
 [1 2 0]
 [1 2 3]
 [1 4 0]
 [1 3 4]
 [1 1 1]]

24
[[2 0 2]
 [2 2 2]
 [2 1 0]
 [2 1 3]
 [2 4 2]
 [2 3 0]
 [2 3 3]
 [2 0 1]
 [2 2 4]
 [2 1 2]
 [2 0 4]
 [2 2 1]
 [2 3 2]
 [2 4 1]
 [2 4 4]
 [2 0 0]
 [2 0 3]
 [2 2 0]
 [2 1 4]
 [2 2 3]
 [2 1 1]
 [2 4 0]
 [2 4 3]
 [2 3 1]]

16
[[3 2 1]
 [3 1 2]
 [3 4 1]
 [3 3 2]
 [3 0 0]
 [3 1 1]
 [3 2 0]
 [3 4 3]
 [3 3 1]
 [3 2 3]
 [3 1 4]
 [3 2 2]
 [3 3 3]
 [3 4 2]
 [3 3 0]
 [3 1 0]]



In [16]:
print(set(matrice[:,0]))
print(set(matrice[:,1]))
print(set(matrice[:,2]))

np_array_recherche = np.array([0,0,0])
presence = any(np.array_equal(np_array_recherche, array) for array in pav)
print(presence)

{0, 1, 2, 3}
{0, 1, 2, 3, 4}
{0, 1, 2, 3, 4}
True


In [17]:
import numpy as np
v1=[np.array([0,0,0,0]), np.array([1,2,3,4]), np.array([1,2,3,3]), np.array([1,2,2,2]), np.array([1,1,1,1])]
v2=[np.array([0,0,0,0]), np.array([1,2,3,5]), np.array([1,2,3,0]), np.array([1,2,2,0]), np.array([1,1,1,0])]
v3=[np.array([0,0,0,0]), np.array([1,2,4,5]), np.array([1,2,5,0]), np.array([1,2,0,0]), np.array([1,1,0,0])]
v4=[np.array([0,0,0,0]), np.array([1,3,4,5]), np.array([1,4,5,0]), np.array([1,5,0,0]), np.array([1,0,0,0])] 

for x in v1:
    for y in v2:
        for z in v3:
            for a in v4:
                print(x,"+",y,"+",z,"+",a,"=",np.array([(x[0]+y[0]+z[0]+a[0]),(x[1]+y[1]+z[1]+a[1])%6, 
                                                  (x[2]+y[2]+z[2]+a[2])%6,(x[3]+y[3]+z[3]+a[3])%6  ]))


PAV= [np.array([(x[0]+y[0]+z[0]+a[0]),(x[1]+y[1]+z[1]+a[1])%6,
                (x[2]+y[2]+z[2]+a[2])%6,(x[3]+y[3]+z[3]+a[3])%6  ])  
                for x in v1 for y in v2 for z in v3 for a in v4]


[0 0 0 0] + [0 0 0 0] + [0 0 0 0] + [0 0 0 0] = [0 0 0 0]
[0 0 0 0] + [0 0 0 0] + [0 0 0 0] + [1 3 4 5] = [1 3 4 5]
[0 0 0 0] + [0 0 0 0] + [0 0 0 0] + [1 4 5 0] = [1 4 5 0]
[0 0 0 0] + [0 0 0 0] + [0 0 0 0] + [1 5 0 0] = [1 5 0 0]
[0 0 0 0] + [0 0 0 0] + [0 0 0 0] + [1 0 0 0] = [1 0 0 0]
[0 0 0 0] + [0 0 0 0] + [1 2 4 5] + [0 0 0 0] = [1 2 4 5]
[0 0 0 0] + [0 0 0 0] + [1 2 4 5] + [1 3 4 5] = [2 5 2 4]
[0 0 0 0] + [0 0 0 0] + [1 2 4 5] + [1 4 5 0] = [2 0 3 5]
[0 0 0 0] + [0 0 0 0] + [1 2 4 5] + [1 5 0 0] = [2 1 4 5]
[0 0 0 0] + [0 0 0 0] + [1 2 4 5] + [1 0 0 0] = [2 2 4 5]
[0 0 0 0] + [0 0 0 0] + [1 2 5 0] + [0 0 0 0] = [1 2 5 0]
[0 0 0 0] + [0 0 0 0] + [1 2 5 0] + [1 3 4 5] = [2 5 3 5]
[0 0 0 0] + [0 0 0 0] + [1 2 5 0] + [1 4 5 0] = [2 0 4 0]
[0 0 0 0] + [0 0 0 0] + [1 2 5 0] + [1 5 0 0] = [2 1 5 0]
[0 0 0 0] + [0 0 0 0] + [1 2 5 0] + [1 0 0 0] = [2 2 5 0]
[0 0 0 0] + [0 0 0 0] + [1 2 0 0] + [0 0 0 0] = [1 2 0 0]
[0 0 0 0] + [0 0 0 0] + [1 2 0 0] + [1 3 4 5] = [2 5 4 5]
[0 0 0 0] + [0

In [18]:
#print(PAV)

ensemble_unique = set(map(tuple, PAV))

# Convertir chaque tuple unique en np.array
pav = [np.array(x) for x in ensemble_unique]

#print(pav)

print(len(PAV))
print(len(pav))
matrice=np.stack(pav)
#print(matrice)
matrice1= []
for i in range(5):
    matrice1.append([])

for element in matrice:
    matrice1[element[0]].append(element)

for element in matrice1:
    truc = np.stack(element)
    print(len(truc))
    print(truc)
    print()

625
432
1
[[0 0 0 0]]

16
[[1 2 5 0]
 [1 4 5 0]
 [1 2 0 0]
 [1 1 0 0]
 [1 1 1 1]
 [1 3 4 5]
 [1 2 3 5]
 [1 2 3 0]
 [1 5 0 0]
 [1 2 3 4]
 [1 2 2 2]
 [1 2 4 5]
 [1 1 1 0]
 [1 0 0 0]
 [1 2 3 3]
 [1 2 2 0]]

90
[[2 1 1 1]
 [2 3 4 4]
 [2 2 5 0]
 [2 4 5 2]
 [2 3 5 5]
 [2 0 1 1]
 [2 4 2 5]
 [2 5 1 5]
 [2 1 1 0]
 [2 3 5 0]
 [2 4 2 0]
 [2 4 1 4]
 [2 3 4 3]
 [2 0 0 0]
 [2 4 5 1]
 [2 3 0 1]
 [2 5 1 4]
 [2 1 4 5]
 [2 4 5 5]
 [2 5 4 5]
 [2 0 3 5]
 [2 2 0 0]
 [2 2 1 1]
 [2 4 1 3]
 [2 1 3 4]
 [2 4 5 0]
 [2 3 0 0]
 [2 3 3 1]
 [2 0 2 3]
 [2 4 0 2]
 [2 2 1 0]
 [2 4 1 2]
 [2 2 4 5]
 [2 1 3 3]
 [2 3 3 5]
 [2 2 3 5]
 [2 3 3 0]
 [2 4 0 1]
 [2 2 3 0]
 [2 3 3 4]
 [2 4 0 5]
 [2 2 3 4]
 [2 1 2 0]
 [2 3 2 2]
 [2 5 2 4]
 [2 0 1 0]
 [2 2 2 2]
 [2 4 2 4]
 [2 2 3 3]
 [2 4 3 5]
 [2 4 3 0]
 [2 2 2 1]
 [2 4 2 3]
 [2 3 1 1]
 [2 5 1 3]
 [2 4 5 4]
 [2 5 5 0]
 [2 3 4 1]
 [2 1 5 0]
 [2 0 4 0]
 [2 5 0 1]
 [2 3 1 0]
 [2 5 1 2]
 [2 4 5 3]
 [2 5 0 5]
 [2 3 4 0]
 [2 5 0 0]
 [2 4 1 5]
 [2 1 0 0]
 [2 4 1 0]
 [2 4 4 2]
 [2 3 3 3]
 

In [19]:
print(set(matrice[:,0]))
print(set(matrice[:,1]))
print(set(matrice[:,2]))
print(set(matrice[:,3]))

np_array_recherche = np.array([3,4,2,5])
presence = any(np.array_equal(np_array_recherche, array) for array in pav)
print(presence)

{0, 1, 2, 3, 4}
{0, 1, 2, 3, 4, 5}
{0, 1, 2, 3, 4, 5}
{0, 1, 2, 3, 4, 5}
True


In [20]:
import numpy as np
#v1= [np.array([0,0,0]), np.array([3,-1,-1]), np.array([2,0,-1]), np.array([1,0,0]) ]
#v2= [np.array([0,0,0]), np.array([4,-2,-1]), np.array([5,-3,-1]), np.array([5,-4,0]) ]
#v3= [np.array([0,0,0]), np.array([4,-1,-2]), np.array([5,-1,-3]), np.array([5,0,-4]) ]


#v1= [np.array([0,0,0]), np.array([1,-1,-2]), np.array([1,0,-3]), np.array([1,0,-4]) ]
#v2= [np.array([0,0,0]), np.array([1,-2,-1]), np.array([1,-3,0]), np.array([1,-4,0]) ]
#v3= [np.array([0,0,0]), np.array([1,-1,-1]), np.array([1,-1,0]), np.array([1,0,0]) ]


v1= [np.array([0,0,0]), np.array([1,4,3]), np.array([1,0,2]), np.array([1,0,1]) ]
v2= [np.array([0,0,0]), np.array([1,3,4]), np.array([1,2,0]), np.array([1,1,0]) ]
v3= [np.array([0,0,0]), np.array([1,4,4]), np.array([1,4,0]), np.array([1,0,0]) ]

'''
for x in v1:
    for y in v2:
        for z in v3:
            print(x,"+",y,"+",z,"=",np.array([(x[0]+y[0]+z[0]),(x[1]+y[1]+z[1]), (x[2]+y[2]+z[2]) ]))
'''




PAV= [np.array([(x[0]+y[0]+z[0]),(x[1]+y[1]+z[1]), (x[2]+y[2]+z[2]) ])  
         for x in v1 for y in v2 for z in v3]
#print(PAV)

ensemble_unique = set(map(tuple, PAV))

# Convertir chaque tuple unique en np.array
pav = [np.array(x) for x in ensemble_unique]

#print(pav)

print(len(PAV))
print(len(pav))
matrice=np.stack(pav)
#print(matrice)


matrice1= []
for i in range(4):
    matrice1.append([])

for element in matrice:
    matrice1[element[0]].append(element)

for element in matrice1:
    truc = np.stack(element)
    print(len(truc))
    print(truc)
    print()

64
64
1
[[0 0 0]]

9
[[1 0 1]
 [1 1 0]
 [1 4 4]
 [1 0 0]
 [1 2 0]
 [1 4 0]
 [1 3 4]
 [1 4 3]
 [1 0 2]]

27
[[2 8 3]
 [2 0 2]
 [2 2 2]
 [2 1 0]
 [2 7 4]
 [2 5 4]
 [2 7 7]
 [2 4 2]
 [2 4 6]
 [2 4 5]
 [2 3 6]
 [2 0 1]
 [2 1 2]
 [2 2 1]
 [2 5 0]
 [2 5 3]
 [2 6 4]
 [2 4 1]
 [2 3 5]
 [2 8 7]
 [2 2 0]
 [2 1 1]
 [2 6 0]
 [2 6 3]
 [2 7 8]
 [2 3 4]
 [2 4 3]]

27
[[ 3 11  7]
 [ 3  5  3]
 [ 3  5  6]
 [ 3  7  6]
 [ 3  7  9]
 [ 3  2  1]
 [ 3  1  2]
 [ 3  3  5]
 [ 3  6  1]
 [ 3  9  3]
 [ 3  5  2]
 [ 3  7  5]
 [ 3  5  5]
 [ 3  1  1]
 [ 3 10  7]
 [ 3  6  3]
 [ 3  6  6]
 [ 3 11 11]
 [ 3  5  1]
 [ 3 10  3]
 [ 3  7 10]
 [ 3  7  7]
 [ 3  2  2]
 [ 3  3  6]
 [ 3  6  2]
 [ 3  6  5]
 [ 3  9  7]]



In [21]:
from itertools import product
import numpy as np

def product_sums(*listes):

    combinaisons = product(*listes)
    resultats = [sum(combinaison) for combinaison in combinaisons]
    
    return resultats



#v1= [np.array([0,0,0]), np.array([1,-1,-2]), np.array([1,0,-3]), np.array([1,0,-4]) ]
#v2= [np.array([0,0,0]), np.array([1,-2,-1]), np.array([1,-3,0]), np.array([1,-4,0]) ]
#v3= [np.array([0,0,0]), np.array([1,-1,-1]), np.array([1,-1,0]), np.array([1,0,0]) ]

v1= [np.array([0,0,0]), np.array([1,4,3]), np.array([1,0,2]), np.array([1,0,1]) ]
v2= [np.array([0,0,0]), np.array([1,3,4]), np.array([1,2,0]), np.array([1,1,0]) ]
v3= [np.array([0,0,0]), np.array([1,4,4]), np.array([1,4,0]), np.array([1,0,0]) ]


a=({(1, 0, 0): [0, 0, 0, 0], (1, 2, 0): [1, 5, 5, 4], (1, 3, 0): [1, 5, 0, 3],
   (1, 4, 0): [1, 0, 0, 2], (1, 5, 0): [1, 0, 0, 1], 
  (2, 0, 0): [0, 0, 0, 0], (2, 1, 0): [1, 5, 4, 5], (2, 3, 0): [1, 5, 3, 0], 
  (2, 4, 0): [1, 0, 2, 0], (2, 5, 0): [1, 0, 1, 0], 
  (3, 0, 0): [0, 0, 0, 0], (3, 1, 0): [1, 4, 5, 5], (3, 2, 0): [1, 3, 5, 0], 
  (3, 4, 0): [1, 2, 0, 0], (3, 5, 0): [1, 1, 0, 0], 
  (4, 0, 0): [0, 0, 0, 0], (4, 1, 0): [1, 5, 5, 5], (4, 2, 0): [1, 5, 5, 0],
    (4, 3, 0): [1, 5, 0, 0], (4, 5, 0): [1, 0, 0, 0]}, 
 [0, 6, 6, 6])


b=({(1, 0, 0): [0, 0, 0, 0], (1, 2, 0): [1, 2, 3, 4], (1, 3, 0): [1, 2, 3, 3],
   (1, 4, 0): [1, 2, 2, 2], (1, 5, 0): [1, 1, 1, 1], 
   (2, 0, 0): [0, 0, 0, 0], (2, 1, 0): [1, 2, 3, 5], (2, 3, 0): [1, 2, 3, 0],
     (2, 4, 0): [1, 2, 2, 0], (2, 5, 0): [1, 1, 1, 0], 
     (3, 0, 0): [0, 0, 0, 0], (3, 1, 0): [1, 2, 4, 5], (3, 2, 0): [1, 2, 5, 0], 
     (3, 4, 0): [1, 2, 0, 0], (3, 5, 0): [1, 1, 0, 0], 
     (4, 0, 0): [0, 0, 0, 0], (4, 1, 0): [1, 3, 4, 5], (4, 2, 0): [1, 4, 5, 0], 
     (4, 3, 0): [1, 5, 0, 0], (4, 5, 0): [1, 0, 0, 0]},
  [0, 6, 6, 6])

'''
v1= [np.array([0, 0, 0, 0]), np.array([1, 5, 5, 4]), np.array([1, 5, 0, 3]), 
     np.array([1, 0, 0, 2]), np.array([1, 0, 0, 1]) ]
v2= [np.array([0, 0, 0, 0]), np.array([1, 5, 4, 5]), np.array([1, 5, 3, 0]), 
     np.array([1, 0, 2, 0]), np.array([1, 0, 1, 0]) ]
v3= [np.array([0, 0, 0, 0]), np.array([1, 4, 5, 5]), np.array([1, 3, 5, 0]), 
     np.array([1, 2, 0, 0]), np.array([1, 1, 0, 0]) ]
v4= [np.array([0, 0, 0, 0]), np.array([1, 5, 5, 5]), np.array([1, 5, 5, 0]), 
     np.array([1, 5, 0, 0]), np.array([1, 0, 0, 0]) ]



orders= [1000, 6, 6, 6]
'''
orders= [1000, 5, 5]
resultats = product_sums(v1,v2,v3)



ensemble_unique = set(map(tuple, resultats))
pav = [np.array(x) for x in ensemble_unique]
matrice=np.stack(pav)

print(len(pav))
#print(matrice)


matrice2 = []
for element in matrice:
     matrice2.append([element[i]%orders[i] for i in range(len(element))])


matrice2 = np.array(matrice2)
matrice = np.unique(matrice2, axis=0)
print(len(matrice))

matrice1= []
n=4
for i in range(n):
    matrice1.append([])

for element in matrice:
    matrice1[element[0]].append(element)
#print(matrice1)


for element in matrice1:
    truc = np.stack(element)
    print(len(truc))
    print(truc)
    print()




64
50
1
[[0 0 0]]

9
[[1 0 0]
 [1 0 1]
 [1 0 2]
 [1 1 0]
 [1 2 0]
 [1 3 4]
 [1 4 0]
 [1 4 3]
 [1 4 4]]

24
[[2 0 0]
 [2 0 1]
 [2 0 2]
 [2 0 3]
 [2 0 4]
 [2 1 0]
 [2 1 1]
 [2 1 2]
 [2 1 3]
 [2 1 4]
 [2 2 0]
 [2 2 1]
 [2 2 2]
 [2 2 3]
 [2 2 4]
 [2 3 0]
 [2 3 1]
 [2 3 2]
 [2 3 3]
 [2 3 4]
 [2 4 0]
 [2 4 1]
 [2 4 2]
 [2 4 3]]

16
[[3 0 0]
 [3 0 1]
 [3 0 2]
 [3 0 3]
 [3 1 0]
 [3 1 1]
 [3 1 2]
 [3 1 3]
 [3 2 0]
 [3 2 1]
 [3 2 2]
 [3 2 4]
 [3 3 0]
 [3 3 1]
 [3 4 2]
 [3 4 3]]



In [22]:
from itertools import product
import numpy as np

def product_sums(*listes):

    combinaisons = product(*listes)
    resultats = [sum(combinaison) for combinaison in combinaisons]
    
    return resultats






v1= [np.array([0, 0, 0, 0]), np.array([1, 5, 5, 4]), np.array([1, 5, 0, 3]), 
     np.array([1, 0, 0, 2]), np.array([1, 0, 0, 1]) ]
v2= [np.array([0, 0, 0, 0]), np.array([1, 5, 4, 5]), np.array([1, 5, 3, 0]), 
     np.array([1, 0, 2, 0]), np.array([1, 0, 1, 0]) ]
v3= [np.array([0, 0, 0, 0]), np.array([1, 4, 5, 5]), np.array([1, 3, 5, 0]), 
     np.array([1, 2, 0, 0]), np.array([1, 1, 0, 0]) ]
v4= [np.array([0, 0, 0, 0]), np.array([1, 5, 5, 5]), np.array([1, 5, 5, 0]), 
     np.array([1, 5, 0, 0]), np.array([1, 0, 0, 0]) ]



orders= [1000, 6, 6, 6]

#orders= [1000, 5, 5]
resultats = product_sums(v1,v2,v3,v4)



ensemble_unique = set(map(tuple, resultats))
pav = [np.array(x) for x in ensemble_unique]
matrice=np.stack(pav)

print(len(pav))
#print(matrice)


matrice2 = []
for element in matrice:
     matrice2.append([element[i]%orders[i] for i in range(len(element))])


matrice2 = np.array(matrice2)
matrice = np.unique(matrice2, axis=0)
print(len(matrice))

matrice1= []
n=5
for i in range(n):
    matrice1.append([])



for element in matrice:
    matrice1[element[0]].append(element)


#print(matrice1)

'''
for element in matrice1:
    truc = np.stack(element)
    print(len(truc))
    #print(truc)
    #print()
'''

truc = np.stack(matrice1[2])
print(len(truc))
for el in truc:
    print(el)



625
432
90
[2 0 0 0]
[2 0 0 1]
[2 0 0 2]
[2 0 0 3]
[2 0 1 0]
[2 0 1 1]
[2 0 1 2]
[2 0 2 0]
[2 0 2 1]
[2 0 2 2]
[2 0 3 0]
[2 0 4 5]
[2 0 5 0]
[2 0 5 4]
[2 0 5 5]
[2 1 0 0]
[2 1 0 1]
[2 1 0 2]
[2 1 0 3]
[2 1 1 0]
[2 1 2 0]
[2 1 3 0]
[2 1 4 5]
[2 1 5 0]
[2 1 5 4]
[2 1 5 5]
[2 2 0 0]
[2 2 0 1]
[2 2 0 2]
[2 2 1 0]
[2 2 2 0]
[2 2 3 5]
[2 2 4 0]
[2 2 4 4]
[2 2 4 5]
[2 2 5 0]
[2 2 5 3]
[2 3 0 0]
[2 3 1 0]
[2 3 2 5]
[2 3 3 4]
[2 3 4 3]
[2 3 4 4]
[2 3 4 5]
[2 3 5 0]
[2 3 5 1]
[2 3 5 2]
[2 3 5 5]
[2 4 0 3]
[2 4 0 5]
[2 4 1 5]
[2 4 2 0]
[2 4 2 4]
[2 4 2 5]
[2 4 3 0]
[2 4 3 3]
[2 4 3 4]
[2 4 3 5]
[2 4 4 2]
[2 4 4 3]
[2 4 4 4]
[2 4 4 5]
[2 4 5 0]
[2 4 5 1]
[2 4 5 2]
[2 4 5 3]
[2 4 5 4]
[2 4 5 5]
[2 5 0 0]
[2 5 0 1]
[2 5 0 2]
[2 5 0 3]
[2 5 0 4]
[2 5 0 5]
[2 5 1 0]
[2 5 1 3]
[2 5 1 4]
[2 5 1 5]
[2 5 2 0]
[2 5 2 3]
[2 5 3 0]
[2 5 3 1]
[2 5 3 2]
[2 5 4 0]
[2 5 4 1]
[2 5 4 5]
[2 5 5 0]
[2 5 5 1]
[2 5 5 2]
[2 5 5 4]


In [168]:
from itertools import product
import numpy as np

def product_sums(*listes):

    combinaisons = product(*listes)
    resultats = [sum(combinaison) for combinaison in combinaisons]
    
    return resultats



v1= [np.array([0, 0, 0, 0, 0]), np.array([1, 6, 6, 6, 5]), np.array([1, 6, 6, 0, 4]), 
     np.array([1, 6, 0, 0, 3]), np.array([1, 0, 0, 0, 2]), np.array([1, 0, 0, 0, 1]) ]
v2= [np.array([0, 0, 0, 0, 0]), np.array([1, 6, 6, 5, 6]), np.array([1, 6, 6, 4, 0]), 
     np.array([1, 6, 0, 3, 0]), np.array([1, 0, 0, 2, 0]), np.array([1, 0, 0, 1, 0]) ]
v3= [np.array([0, 0, 0, 0, 0]), np.array([1, 6, 5, 6, 6]), np.array([1, 6, 4, 6, 0]), 
     np.array([1, 6, 3, 0, 0]), np.array([1, 0, 2, 0, 0]), np.array([1, 0, 1, 0, 0]) ]
v4= [np.array([0, 0, 0, 0, 0]), np.array([1, 5, 6, 6, 6]), np.array([1, 4, 6, 6, 0]), 
     np.array([1, 3, 6, 0, 0]), np.array([1, 2, 0, 0, 0]), np.array([1, 1, 0, 0, 0]) ]
v5= [np.array([0, 0, 0, 0, 0]), np.array([1, 6, 6, 6, 6]), np.array([1, 6, 6, 6, 0]), 
     np.array([1, 6, 6, 0, 0]), np.array([1, 6, 0, 0, 0]), np.array([1, 0, 0, 0, 0]) ]



V1 = [np.array([0, 0, 0, 0, 0]), np.array([1, 5, 6, 6, 6]), np.array([1, 4, 0, 6, 6]),
     np.array([1, 3, 0, 0, 6]), np.array([1, 2, 0, 0, 0]), np.array([1, 1, 0, 0, 0])]
V2 = [np.array([0, 0, 0, 0, 0]), np.array([1, 6, 5, 6, 6]), np.array([1, 0, 4, 6, 6]),
     np.array([1, 0, 3, 0, 6]), np.array([1, 0, 2, 0, 0]), np.array([1, 0, 1, 0, 0])]
V3 = [np.array([0, 0, 0, 0, 0]), np.array([1, 6, 6, 5, 6]), np.array([1, 0, 6, 4, 6]), 
     np.array([1, 0, 0, 3, 6]), np.array([1, 0, 0, 2, 0]), np.array([1, 0, 0, 1, 0])]
V4 = [np.array([0, 0, 0, 0, 0]), np.array([1, 6, 6, 6, 5]), np.array([1, 0, 6, 6, 4]), 
     np.array([1, 0, 0, 6, 3]), np.array([1, 0, 0, 0, 2]), np.array([1, 0, 0, 0, 1])]
V5 = [np.array([0, 0, 0, 0, 0]), np.array([1, 6, 6, 6, 6]), np.array([1, 0, 6, 6, 6]), 
     np.array([1, 0, 0, 6, 6]), np.array([1, 0, 0, 0, 6]), np.array([1, 0, 0, 0, 0])]





V1 = [np.array([0, 0, 0, 0, 0]), np.array([1, 2, 1, 1, 1]), np.array([1, 3, 0, 1, 1]),
     np.array([1, 4, 0, 0, 1]), np.array([1, 5, 0, 0, 0]), np.array([1, 6, 0, 0, 0])]
V2 = [np.array([0, 0, 0, 0, 0]), np.array([1, 1, 2, 1, 1]), np.array([1, 0, 3, 1, 1]), 
     np.array([1, 0, 4, 0, 1]), np.array([1, 0, 5, 0, 0]), np.array([1, 0, 6, 0, 0])]
V3 = [np.array([0, 0, 0, 0, 0]), np.array([1, 1, 1, 2, 1]), np.array([1, 0, 1, 3, 1]), 
     np.array([1, 0, 0, 4, 1]), np.array([1, 0, 0, 5, 0]), np.array([1, 0, 0, 6, 0])]
V4 = [np.array([0, 0, 0, 0, 0]), np.array([1, 1, 1, 1, 2]), np.array([1, 0, 1, 1, 3]), 
     np.array([1, 0, 0, 1, 4]), np.array([1, 0, 0, 0, 5]), np.array([1, 0, 0, 0, 6])]
V5 = [np.array([0, 0, 0, 0, 0]), np.array([1, 1, 1, 1, 1]), np.array([1, 0, 1, 1, 1]), 
     np.array([1, 0, 0, 1, 1]), np.array([1, 0, 0, 0, 1]), np.array([1, 0, 0, 0, 0])]




orders = [1000, 7, 7, 7, 7]


#orders= [1000, 6, 6, 6]
#orders= [1000, 5, 5]
resultats = product_sums(V1,V2,V3,V4,V5)
#resultats = product_sums(V2,V3,V4,V5)


ensemble_unique = set(map(tuple, resultats))
pav = [np.array(x) for x in ensemble_unique]
matrice=np.stack(pav)

print(len(pav))
#print(matrice)


matrice2 = []
for element in matrice:
     matrice2.append([element[i]%orders[i] for i in range(len(element))])


matrice2 = np.array(matrice2)
matrice = np.unique(matrice2, axis=0)
print(len(matrice))

matrice1= []
n=6
for i in range(n):
    matrice1.append([])



for element in matrice:
    matrice1[element[0]].append(element)


#print(matrice1)


#for element in matrice1:
    #truc = np.stack(element)
    #print(len(truc))
    #print(truc)
    #print()

truc = []
for i in range(len(matrice1)):
    truc.append(np.stack(matrice1[i]))
    




#s=[0, V1[5], V2[5], V3[5], V4[5], V5[5]]


# for i in range(len(truc)-1):
#      for rho in truc[i]:
#           element = rho-s[1]
#           np_array_recherche =  np.array([element[i]%orders[i] for i in range(len(element))])
#           presence = any(np.array_equal(np_array_recherche, array) for array in matrice)
#           if presence:
#                print(rho, " - ", s[1], " ==    ", np_array_recherche)
#      print("\n\n")


for el in truc:
    print(len(el))


for el in truc[3]:
    print(el)
    




# np_array_recherche = np.array([3,0,6,5,4])
# presence = any(np.array_equal(np_array_recherche, array) for array in matrice)
# print(presence)

4802
4802
1
25
240
1080
2160
1296
[3 0 0 0 0]
[3 0 0 0 1]
[3 0 0 0 3]
[3 0 0 0 4]
[3 0 0 0 5]
[3 0 0 0 6]
[3 0 0 1 0]
[3 0 0 1 1]
[3 0 0 1 2]
[3 0 0 1 3]
[3 0 0 1 4]
[3 0 0 1 5]
[3 0 0 1 6]
[3 0 0 2 1]
[3 0 0 2 4]
[3 0 0 2 5]
[3 0 0 3 0]
[3 0 0 3 1]
[3 0 0 3 2]
[3 0 0 3 6]
[3 0 0 4 0]
[3 0 0 4 1]
[3 0 0 4 2]
[3 0 0 4 4]
[3 0 0 4 5]
[3 0 0 4 6]
[3 0 0 5 0]
[3 0 0 5 1]
[3 0 0 5 2]
[3 0 0 5 4]
[3 0 0 5 5]
[3 0 0 5 6]
[3 0 0 6 0]
[3 0 0 6 1]
[3 0 0 6 3]
[3 0 0 6 4]
[3 0 0 6 5]
[3 0 0 6 6]
[3 0 1 0 0]
[3 0 1 0 1]
[3 0 1 0 2]
[3 0 1 0 3]
[3 0 1 0 4]
[3 0 1 0 5]
[3 0 1 0 6]
[3 0 1 1 0]
[3 0 1 1 2]
[3 0 1 1 3]
[3 0 1 1 4]
[3 0 1 1 5]
[3 0 1 1 6]
[3 0 1 2 0]
[3 0 1 2 1]
[3 0 1 2 2]
[3 0 1 2 3]
[3 0 1 2 4]
[3 0 1 2 5]
[3 0 1 2 6]
[3 0 1 3 0]
[3 0 1 3 1]
[3 0 1 3 2]
[3 0 1 3 5]
[3 0 1 3 6]
[3 0 1 4 0]
[3 0 1 4 1]
[3 0 1 4 2]
[3 0 1 4 4]
[3 0 1 4 5]
[3 0 1 4 6]
[3 0 1 5 0]
[3 0 1 5 1]
[3 0 1 5 2]
[3 0 1 5 3]
[3 0 1 5 4]
[3 0 1 5 5]
[3 0 1 5 6]
[3 0 1 6 0]
[3 0 1 6 1]
[3 0 1 6 2]
[3 0 1 6 3]
[3 0 1

In [94]:
from math import comb

def f(n:int):
    resultat = 0
    for k in range(n-1):
        resultat += comb(n-2,k) * ((k+1)**(k-1)) * ((n-1-k)**(n-3-k))
    return resultat



def g(n:int):
    return 2*((n)**(n-3))


n=10
print(f(n)-g(n), f(n), g(n))




0.0 20000000.0 20000000


In [106]:
from itertools import product
import numpy as np

def product_sums(*listes):

    combinaisons = product(*listes)
    resultats = [sum(combinaison) for combinaison in combinaisons]
    
    return resultats



V1 = [np.array([0, 0, 0, 0, 0]), np.array([0, 1, 6, 0, 0]), np.array([0, 2, 6, 6, 0]), np.array([0, 3, 6, 6, 6]), np.array([0, 4, 6, 6, 6]), np.array([-1,5, 6, 6, 6])]
V2 = [np.array([0, 0, 0, 0, 0]), np.array([0, 0, 1, 6, 0]), np.array([0, 0, 2, 6, 6]), np.array([0, 0, 3, 6, 6]), np.array([-1,0, 4, 6, 6]), np.array([0, 1, 6, 0, 0])]
V3 = [np.array([0, 0, 0, 0, 0]), np.array([0, 0, 0, 1, 6]), np.array([0, 0, 0, 2, 6]), np.array([-1,0, 0, 3, 6]), np.array([0, 1, 1, 5, 0]), np.array([0, 0, 1, 6, 0])]
V4 = [np.array([0, 0, 0, 0, 0]), np.array([0, 0, 0, 0, 1]), np.array([-1,0, 0, 0, 2]), np.array([0, 1, 1, 1, 4]), np.array([0, 0, 1, 1, 5]), np.array([0, 0, 0, 1, 6])]
V5 = [np.array([0, 0, 0, 0, 0]), np.array([-1,0, 0, 0, 0]), np.array([0, 1, 1, 1, 1]), np.array([0, 0, 1, 1, 1]), np.array([0, 0, 0, 1, 1]), np.array([0, 0, 0, 0, 1])]




orders = [-1000, 7, 7, 7, 7]


#orders= [1000, 6, 6, 6]
#orders= [1000, 5, 5]
resultats = product_sums(V1,V2,V3,V4,V5)
#resultats = product_sums(V2,V3,V4,V5)


ensemble_unique = set(map(tuple, resultats))
pav = [np.array(x) for x in ensemble_unique]
matrice=np.stack(pav)

print(len(pav))
#print(matrice)


matrice2 = []
for element in matrice:
     matrice2.append([element[i]%orders[i] for i in range(len(element))])


matrice2 = np.array(matrice2)
matrice = np.unique(matrice2, axis=0)
print(len(matrice))



matrice1= dict()
n=6
for i in range(n):
    matrice1[-i] = []



for element in matrice:
    print(element)
    #matrice1[element[0]]=  matrice1[element[0]].append(element)


#print(matrice)


#for element in matrice1:
    #truc = np.stack(element)
    #print(len(truc))
    #print(truc)
    #print()

'''
truc = []
for i in range(len(matrice1)):
    truc.append(np.stack(matrice1[i]))
'''  




#s=[0, V1[5], V2[5], V3[5], V4[5], V5[5]]


# for i in range(len(truc)-1):
#      for rho in truc[i]:
#           element = rho-s[1]
#           np_array_recherche =  np.array([element[i]%orders[i] for i in range(len(element))])
#           presence = any(np.array_equal(np_array_recherche, array) for array in matrice)
#           if presence:
#                print(rho, " - ", s[1], " ==    ", np_array_recherche)
#      print("\n\n")

'''
for el in truc:
    print(len(el))


for el in truc[3]:
    print(el)
'''    




# np_array_recherche = np.array([3,0,6,5,4])
# presence = any(np.array_equal(np_array_recherche, array) for array in matrice)
# print(presence)

6115
4802
[-5  5  3  1  6]
[-4  0  4  2  0]
[-4  1  3  2  0]
[-4  2  3  1  0]
[-4  3  3  1  6]
[-4  4  3  1  6]
[-4  5  0  1  0]
[-4  5  1  1  6]
[-4  5  2  1  6]
[-4  5  3  0  6]
[-4  5  3  1  0]
[-4  5  3  1  4]
[-4  5  3  1  5]
[-4  5  3  1  6]
[-4  5  3  2  0]
[-4  5  3  2  3]
[-4  5  3  5  0]
[-4  5  3  6  6]
[-4  5  4  2  0]
[-4  5  4  2  2]
[-4  5  4  4  0]
[-4  5  6  2  0]
[-4  6  4  2  0]
[-4  6  4  2  1]
[-4  6  4  3  0]
[-4  6  5  2  0]
[-3  0  0  3  1]
[-3  0  1  2  1]
[-3  0  2  2  0]
[-3  0  3  2  0]
[-3  0  4  0  0]
[-3  0  4  1  0]
[-3  0  4  2  0]
[-3  0  4  2  1]
[-3  0  4  2  5]
[-3  0  4  2  6]
[-3  0  4  3  1]
[-3  0  4  3  4]
[-3  0  4  6  1]
[-3  0  5  3  1]
[-3  0  5  3  2]
[-3  0  5  3  3]
[-3  0  5  4  1]
[-3  0  5  4  2]
[-3  0  5  5  1]
[-3  0  6  3  1]
[-3  0  6  3  2]
[-3  0  6  4  1]
[-3  1  0  2  1]
[-3  1  1  2  0]
[-3  1  2  2  0]
[-3  1  3  0  0]
[-3  1  3  1  0]
[-3  1  3  2  0]
[-3  1  3  2  1]
[-3  1  3  2  5]
[-3  1  3  2  6]
[-3  1  3  3  1]
[-3 

'\nfor el in truc:\n    print(len(el))\n\n\nfor el in truc[3]:\n    print(el)\n'

In [115]:

#complete graph on 6 vertices with one sink: 0

from itertools import product
import numpy as np

def product_sums(*listes):

    combinaisons = product(*listes)
    resultats = [sum(combinaison) for combinaison in combinaisons]
    
    return resultats



V1 = [np.array([0, 0, 0, 0]), np.array([2, 1, 1, 1]), np.array([3, 0, 1, 1]), np.array([4, 0, 0, 1]), np.array([5, 0, 0, 0])]
V2 = [np.array([0, 0, 0, 0]), np.array([1, 2, 1, 1]), np.array([0, 3, 1, 1]), np.array([0, 4, 0, 1]), np.array([0, 5, 0, 0])]
V3 = [np.array([0, 0, 0, 0]), np.array([1, 1, 2, 1]), np.array([0, 1, 3, 1]), np.array([0, 0, 4, 1]), np.array([0, 0, 5, 0])]
V4 = [np.array([0, 0, 0, 0]), np.array([1, 1, 1, 2]), np.array([0, 1, 1, 3]), np.array([0, 0, 1, 4]), np.array([0, 0, 0, 5])]
V5 = [np.array([0, 0, 0, 0]), np.array([1, 1, 1, 1]), np.array([0, 1, 1, 1]), np.array([0, 0, 1, 1]), np.array([0, 0, 0, 1])]







orders= [6, 6, 6, 6]
#orders= [1000, 5, 5]
resultats = product_sums(V1,V2,V3,V4,V5)
#resultats = product_sums(V2,V3,V4,V5)


ensemble_unique = set(map(tuple, resultats))
pav = [np.array(x) for x in ensemble_unique]
matrice=np.stack(pav)

print(len(pav))
#print(matrice)




matrice2 = []
for element in matrice:
     matrice2.append([element[i]%orders[i] for i in range(len(element))])


matrice2 = np.array(matrice2)
matrice = np.unique(matrice2, axis=0)
print(len(matrice))

matrice1= []
n=6
for i in range(n):
    matrice1.append([])



for element in matrice:
    matrice1[element[0]].append(element)


# #print(matrice1)


for element in matrice1:
    truc = np.stack(element)
    print(len(truc))
    print(truc)
    print()

# truc = []
# for i in range(len(matrice1)):
#     truc.append(np.stack(matrice1[i]))
    




#s=[0, V1[5], V2[5], V3[5], V4[5], V5[5]]


# for i in range(len(truc)-1):
#      for rho in truc[i]:
#           element = rho-s[1]
#           np_array_recherche =  np.array([element[i]%orders[i] for i in range(len(element))])
#           presence = any(np.array_equal(np_array_recherche, array) for array in matrice)
#           if presence:
#                print(rho, " - ", s[1], " ==    ", np_array_recherche)
#      print("\n\n")


# for el in truc:
#     print(len(el))


# for el in truc[4]:
#     print(el)
    

2160
1296
216
[[0 0 0 0]
 [0 0 0 1]
 [0 0 0 2]
 [0 0 0 3]
 [0 0 0 4]
 [0 0 0 5]
 [0 0 1 0]
 [0 0 1 1]
 [0 0 1 2]
 [0 0 1 3]
 [0 0 1 4]
 [0 0 1 5]
 [0 0 2 0]
 [0 0 2 1]
 [0 0 2 2]
 [0 0 2 3]
 [0 0 2 4]
 [0 0 2 5]
 [0 0 3 0]
 [0 0 3 1]
 [0 0 3 2]
 [0 0 3 3]
 [0 0 3 4]
 [0 0 3 5]
 [0 0 4 0]
 [0 0 4 1]
 [0 0 4 2]
 [0 0 4 3]
 [0 0 4 4]
 [0 0 4 5]
 [0 0 5 0]
 [0 0 5 1]
 [0 0 5 2]
 [0 0 5 3]
 [0 0 5 4]
 [0 0 5 5]
 [0 1 0 0]
 [0 1 0 1]
 [0 1 0 2]
 [0 1 0 3]
 [0 1 0 4]
 [0 1 0 5]
 [0 1 1 0]
 [0 1 1 1]
 [0 1 1 2]
 [0 1 1 3]
 [0 1 1 4]
 [0 1 1 5]
 [0 1 2 0]
 [0 1 2 1]
 [0 1 2 2]
 [0 1 2 3]
 [0 1 2 4]
 [0 1 2 5]
 [0 1 3 0]
 [0 1 3 1]
 [0 1 3 2]
 [0 1 3 3]
 [0 1 3 4]
 [0 1 3 5]
 [0 1 4 0]
 [0 1 4 1]
 [0 1 4 2]
 [0 1 4 3]
 [0 1 4 4]
 [0 1 4 5]
 [0 1 5 0]
 [0 1 5 1]
 [0 1 5 2]
 [0 1 5 3]
 [0 1 5 4]
 [0 1 5 5]
 [0 2 0 0]
 [0 2 0 1]
 [0 2 0 2]
 [0 2 0 3]
 [0 2 0 4]
 [0 2 0 5]
 [0 2 1 0]
 [0 2 1 1]
 [0 2 1 2]
 [0 2 1 3]
 [0 2 1 4]
 [0 2 1 5]
 [0 2 2 0]
 [0 2 2 1]
 [0 2 2 2]
 [0 2 2 3]
 [0 2 2 4]
 [0 2 2

In [154]:
#complete graph on 6 vertices with two sinks: 0, n-1

from itertools import product
import numpy as np

def product_sums(*listes):

    combinaisons = product(*listes)
    resultats = [sum(combinaison) for combinaison in combinaisons]
    
    return resultats




V1 = [np.array([0, 0, 0, 0]), np.array([2, 1, 1, 1]), np.array([3, 0, 1, 1]), np.array([4, 0, 0, 1]), np.array([5, 0, 0, 1])]
V2 = [np.array([0, 0, 0, 0]), np.array([1, 2, 1, 1]), np.array([0, 3, 1, 1]), np.array([0, 4, 0, 1]), np.array([0, 5, 0, 1])]
V3 = [np.array([0, 0, 0, 0]), np.array([1, 1, 2, 1]), np.array([0, 1, 3, 1]), np.array([0, 0, 4, 1]), np.array([0, 0, 5, 1])]
V4 = [np.array([0, 0, 0, 0]), np.array([1, 1, 1, 1]), np.array([0, 1, 1, 1]), np.array([0, 0, 1, 1]), np.array([0, 0, 0, 1])]



V1 = [np.array([0, 0, 0, 0, 0]), np.array([2, 1, 1, 1, 1]), np.array([3, 0, 1, 1, 1]), np.array([4, 0, 0, 1, 1]), np.array([5, 0, 0, 0, 1])]
V2 = [np.array([0, 0, 0, 0, 0]), np.array([1, 2, 1, 1, 1]), np.array([0, 3, 1, 1, 1]), np.array([0, 4, 0, 1, 1]), np.array([0, 5, 0, 0, 1])]
V3 = [np.array([0, 0, 0, 0, 0]), np.array([1, 1, 2, 1, 1]), np.array([0, 1, 3, 1, 1]), np.array([0, 0, 4, 1, 1]), np.array([0, 0, 5, 0, 1])]
V4 = [np.array([0, 0, 0, 0, 0]), np.array([1, 1, 1, 2, 1]), np.array([0, 1, 1, 3, 1]), np.array([0, 0, 1, 4, 1]), np.array([0, 0, 0, 5, 1])]






orders= [6, 6, 6, 6, 6]
#orders= [1000, 5, 5]
resultats = product_sums(V1,V2,V3,V4)
#resultats = product_sums(V2,V3,V4,V5)


ensemble_unique = set(map(tuple, resultats))
pav = [np.array(x) for x in ensemble_unique]
matrice=np.stack(pav)

print(len(pav))
#print(matrice)




matrice2 = []
for element in matrice:
     matrice2.append([element[i]%orders[i] for i in range(len(element))])


matrice2 = np.array(matrice2)
matrice = np.unique(matrice2, axis=0)
print(len(matrice))

matrice1= []
n=6
for i in range(n):
    matrice1.append([])



for element in matrice:
    matrice1[element[0]].append(element)


# #print(matrice1)


# for element in matrice1:
#     truc = np.stack(element)
#     print(len(truc))
#     print(truc)
#     print()



matrice3 = []
for element in matrice2:
     matrice3.append([element[i] for i in range(len(element)-1)])

matrice3 = np.array(matrice3)
matrice3 = np.unique(matrice3, axis=0)
print(len(matrice3))

#print(matrice3)


dico = dict()


for element in matrice2:
    np_array_recherche = tuple(element[:-1])  # Convertir la liste en tuple
    if np_array_recherche not in dico.keys():
        dico[np_array_recherche] = []
    dico[np_array_recherche].append(element)


dico2= dict()



print(len(dico))

# for cle in dico.keys():
#     print (dico[cle])

for element in matrice3:
    cle = tuple(element[:]) 
    pos= [ dico[cle][i][-1] for i in range(len(dico[cle]))]
    #print(cle,":",sorted(pos) )
    dico2[cle] = tuple(pos)



#print(dico2)


def regrouper_par_valeur(dictionnaire):
    regroupement = {}
    for cle, valeur in dictionnaire.items():
        if valeur not in regroupement:
            regroupement[valeur] = [cle]
        else:
            regroupement[valeur].append(cle)
    return regroupement

# Exemple d'utilisation

regroupement = regrouper_par_valeur(dico2)


for cle in regroupement.keys():
    print(cle, len(regroupement[cle]))
    for truc in regroupement[cle]:
        truc = list(truc)
        print(sum(truc)%n, end=" ")
    

    print()




# np_array_recherche = np.array([3,0,6,5,4])
# presence = any(np.array_equal(np_array_recherche, array) for array in matrice)
# print(presence)
    

# truc = []
# for i in range(len(matrice1)):
#     truc.append(np.stack(matrice1[i]))
    




#s=[0, V1[5], V2[5], V3[5], V4[5], V5[5]]


# for i in range(len(truc)-1):
#      for rho in truc[i]:
#           element = rho-s[1]
#           np_array_recherche =  np.array([element[i]%orders[i] for i in range(len(element))])
#           presence = any(np.array_equal(np_array_recherche, array) for array in matrice)
#           if presence:
#                print(rho, " - ", s[1], " ==    ", np_array_recherche)
#      print("\n\n")


# for el in truc:
#     print(len(el))


# for el in truc[4]:
#     print(el)
    

432
432
432
432
(0,) 1
0 
(4,) 125
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
(3,) 200
3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
(2,) 90
4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
(1,) 16
5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 


In [195]:
#complete graph on 6 vertices with two sinks: 0, n-1

from itertools import product
import numpy as np

def product_sums(*listes):

    combinaisons = product(*listes)
    resultats = [sum(combinaison) for combinaison in combinaisons]
    
    return resultats




V1 = [np.array([0, 0, 0, 0, 0]), np.array([1, 2, 1, 1, 1]), np.array([1, 3, 0, 1, 1]),
     np.array([1, 4, 0, 0, 1]), np.array([1, 5, 0, 0, 0]), np.array([1, 6, 0, 0, 0])]
V2 = [np.array([0, 0, 0, 0, 0]), np.array([1, 1, 2, 1, 1]), np.array([1, 0, 3, 1, 1]), 
     np.array([1, 0, 4, 0, 1]), np.array([1, 0, 5, 0, 0]), np.array([1, 0, 6, 0, 0])]
V3 = [np.array([0, 0, 0, 0, 0]), np.array([1, 1, 1, 2, 1]), np.array([1, 0, 1, 3, 1]), 
     np.array([1, 0, 0, 4, 1]), np.array([1, 0, 0, 5, 0]), np.array([1, 0, 0, 6, 0])]
V4 = [np.array([0, 0, 0, 0, 0]), np.array([1, 1, 1, 1, 2]), np.array([1, 0, 1, 1, 3]), 
     np.array([1, 0, 0, 1, 4]), np.array([1, 0, 0, 0, 5]), np.array([1, 0, 0, 0, 6])]
V5 = [np.array([0, 0, 0, 0, 0]), np.array([1, 1, 1, 1, 1]), np.array([1, 0, 1, 1, 1]), 
     np.array([1, 0, 0, 1, 1]), np.array([1, 0, 0, 0, 1]), np.array([1, 0, 0, 0, 0])]



V1 = [np.array([0, 0, 0, 0, 0, 0]), np.array([2, 1, 1, 1, 1, 1]), np.array([3, 0, 1, 1, 1, 1]), 
      np.array([4, 0, 0, 1, 1, 1]), np.array([5, 0, 0, 0, 1, 1]), np.array([6, 0, 0, 0, 0, 1])]
V2 = [np.array([0, 0, 0, 0, 0, 0]), np.array([1, 2, 1, 1, 1, 1]), np.array([0, 3, 1, 1, 1, 1]), 
      np.array([0, 4, 0, 1, 1, 1]), np.array([0, 5, 0, 0, 1, 1]), np.array([0, 6, 0, 0, 0, 1])]
V3 = [np.array([0, 0, 0, 0, 0, 0]), np.array([1, 1, 2, 1, 1, 1]), np.array([0, 1, 3, 1, 1, 1]), 
      np.array([0, 0, 4, 1, 1, 1]), np.array([0, 0, 5, 0, 1, 1]), np.array([0, 0, 6, 0, 0, 1])]
V4 = [np.array([0, 0, 0, 0, 0, 0]), np.array([1, 1, 1, 2, 1, 1]), np.array([0, 1, 1, 3, 1, 1]), 
      np.array([0, 0, 1, 4, 1, 1]), np.array([0, 0, 0, 5, 1, 1]), np.array([0, 0, 0, 6, 0, 1])]
V5 = [np.array([0, 0, 0, 0, 0, 0]), np.array([1, 1, 1, 1, 2, 1]), np.array([0, 1, 1, 1, 3, 1]), 
      np.array([0, 0, 1, 1, 4, 1]), np.array([0, 0, 0, 1, 5, 1]), np.array([0, 0, 0, 0, 6, 1])]






n=7
orders= [7, 7, 7, 7, 7, 7]

resultats = product_sums(V1,V2,V3,V4,V5)


ensemble_unique = set(map(tuple, resultats))
pav = [np.array(x) for x in ensemble_unique]
matrice=np.stack(pav)

#print(len(pav))





matrice2 = []
for element in matrice:
     matrice2.append([element[i]%orders[i] for i in range(len(element))])


matrice2 = np.array(matrice2)
matrice = np.unique(matrice2, axis=0)
print(len(matrice))


# for element in matrice:
#      print(element, sum(element)%n)


#matrice= ensemble des valeurs arcmonique modulo l'ordre



'''
######################## Juste pour tester que toutes les valeur sont bien prises pour les valeurs 
#arcmoniques allant de 1 jusqu'à n-3
matrice3 = []
for element in matrice2:
     matrice3.append([element[i] for i in range(len(element)-2)])

matrice3 = np.array(matrice3)
matrice3 = np.unique(matrice3, axis=0)
print(len(matrice3)== n**(n-3))
#print("matrice3\n",matrice3)

###matrice3 regroupe les valeurs acrmonique sans prendre en compte la composante  en 0
###qui compte le nombre d'arcs ne pointant par vers le sommet 0 et la valeur arcmonique en n-2 ajouter.
###########################
'''


matrice1= []
n=6
for i in range(n):
    matrice1.append([])



for element in matrice:
    matrice1[element[-1]].append(element)


# #print(matrice1)


for element in matrice1[3]:
    print(element)
    
#     truc = np.stack(element)
#     print(len(truc))
#     print(truc)
#     print()




# dico = dict()
# for element in matrice2:
#     np_array_recherche = tuple(element[:-1])  # Convertir la liste en tuple
#     if np_array_recherche not in dico.keys():
#         dico[np_array_recherche] = []
#     dico[np_array_recherche].append(element)

# print(len(dico))
# dico2= dict()





# # for cle in dico.keys():
# #     print (dico[cle])

# for element in matrice3:
#     cle = tuple(element[:]) 
#     pos= [ dico[cle][i][-1] for i in range(len(dico[cle]))]
#     #print(cle,":",sorted(pos) )
#     dico2[cle] = tuple(pos)



# #print(dico2)


# def regrouper_par_valeur(dictionnaire):
#     regroupement = {}
#     for cle, valeur in dictionnaire.items():
#         if valeur not in regroupement:
#             regroupement[valeur] = [cle]
#         else:
#             regroupement[valeur].append(cle)
#     return regroupement

# # Exemple d'utilisation

# regroupement = regrouper_par_valeur(dico2)


# for cle in regroupement.keys():
#     print(cle, len(regroupement[cle]))
#     for truc in regroupement[cle]:
#         truc = list(truc)
#         print(sum(truc)%n, end=" ")
    

#     print()




4802
[0 0 0 0 4 3]
[0 0 0 1 3 3]
[0 0 0 3 1 3]
[0 0 0 4 0 3]
[0 0 0 5 6 3]
[0 0 0 6 5 3]
[0 0 1 0 3 3]
[0 0 1 1 2 3]
[0 0 1 2 1 3]
[0 0 1 3 0 3]
[0 0 1 4 6 3]
[0 0 1 5 5 3]
[0 0 1 6 4 3]
[0 0 2 1 1 3]
[0 0 2 4 5 3]
[0 0 2 5 4 3]
[0 0 3 0 1 3]
[0 0 3 1 0 3]
[0 0 3 2 6 3]
[0 0 3 6 2 3]
[0 0 4 0 0 3]
[0 0 4 1 6 3]
[0 0 4 2 5 3]
[0 0 4 4 3 3]
[0 0 4 5 2 3]
[0 0 4 6 1 3]
[0 0 5 0 6 3]
[0 0 5 1 5 3]
[0 0 5 2 4 3]
[0 0 5 4 2 3]
[0 0 5 5 1 3]
[0 0 5 6 0 3]
[0 0 6 0 5 3]
[0 0 6 1 4 3]
[0 0 6 3 2 3]
[0 0 6 4 1 3]
[0 0 6 5 0 3]
[0 0 6 6 6 3]
[0 1 0 0 3 3]
[0 1 0 1 2 3]
[0 1 0 2 1 3]
[0 1 0 3 0 3]
[0 1 0 4 6 3]
[0 1 0 5 5 3]
[0 1 0 6 4 3]
[0 1 1 0 2 3]
[0 1 1 2 0 3]
[0 1 1 3 6 3]
[0 1 1 4 5 3]
[0 1 1 5 4 3]
[0 1 1 6 3 3]
[0 1 2 0 1 3]
[0 1 2 1 0 3]
[0 1 2 2 6 3]
[0 1 2 3 5 3]
[0 1 2 4 4 3]
[0 1 2 5 3 3]
[0 1 2 6 2 3]
[0 1 3 0 0 3]
[0 1 3 1 6 3]
[0 1 3 2 5 3]
[0 1 3 5 2 3]
[0 1 3 6 1 3]
[0 1 4 0 6 3]
[0 1 4 1 5 3]
[0 1 4 2 4 3]
[0 1 4 4 2 3]
[0 1 4 5 1 3]
[0 1 4 6 0 3]
[0 1 5 0 5 3]
[0 1 5 1 4 3]
[

In [191]:
#complete graph on 5 vertices with one sinks: 0

from itertools import product
import numpy as np

def product_sums(*listes):

    combinaisons = product(*listes)
    resultats = [sum(combinaison) for combinaison in combinaisons]
    
    return resultats




V1 = [np.array([0, 0, 0]), np.array([2, 1, 1]), np.array([3, 0, 1]), np.array([4, 0, 1])]
V2 = [np.array([0, 0, 0]), np.array([1, 2, 1]), np.array([0, 3, 1]), np.array([0, 4, 1])]
V3 = [np.array([0, 0, 0]), np.array([1, 1, 1]), np.array([0, 1, 1]), np.array([0, 0, 1])]



n=5
orders= [5, 5, 5]

resultats = product_sums(V1,V2,V3)


ensemble_unique = set(map(tuple, resultats))
pav = [np.array(x) for x in ensemble_unique]
matrice=np.stack(pav)

#print(len(pav))





matrice2 = []
for element in matrice:
     matrice2.append([element[i]%orders[i] for i in range(len(element))])


matrice2 = np.array(matrice2)
matrice = np.unique(matrice2, axis=0)
print(len(matrice))


# for element in matrice:
#      print(element)


#matrice= ensemble des valeurs arcmonique modulo l'ordre



######################## Juste pour tester que toutes les valeur sont bien prises pour les valeurs 
#arcmoniques allant de 1 jusqu'à n-3
matrice3 = []
for element in matrice2:
     matrice3.append([element[i] for i in range(len(element)-1)])

matrice3 = np.array(matrice3)
matrice3 = np.unique(matrice3, axis=0)
print(len(matrice3))
#print("matrice3\n",matrice3)

###matrice3 regroupe les valeurs acrmonique sans prendre en compte la composante  en 0
###qui compte le nombre d'arcs ne pointant par vers le sommet 0 et la valeur arcmonique en n-2 ajouter.
###########################



dico = dict()
for element in matrice2:
    np_array_recherche = tuple(element[:-1])  # Convertir la liste en tuple
    if np_array_recherche not in dico.keys():
        dico[np_array_recherche] = []
    dico[np_array_recherche].append(element)

print(len(dico))

#print(dico)

dico2= dict()





# for cle in dico.keys():
#     print (dico[cle])

for element in matrice3:
    cle = tuple(element[:]) 
    pos= [ dico[cle][i] for i in range(len(dico[cle]))]
    #print(cle,":",sorted(pos) )
    dico2[cle] = pos



print(dico2)

for cle in dico2.keys():
    print(cle, ":", dico2[cle])



# def regrouper_par_valeur(dictionnaire):
#     regroupement = {}
#     for cle, valeur in dictionnaire.items():
#         if valeur not in regroupement:
#             regroupement[valeur] = [cle]
#         else:
#             regroupement[valeur].append(cle)
#     return regroupement



# regroupement = regrouper_par_valeur(dico2)

# for el in regroupement.keys():
#     print(el,regroupement[el])


# for cle in regroupement.keys():
#     print(cle, len(regroupement[cle]))
#     for truc in regroupement[cle]:
#         truc = list(truc)
#         print(sum(truc)%n, end=" ")
    

#     print()


50
25
25
{(0, 0): [array([0, 0, 3]), array([0, 0, 1]), array([0, 0, 0]), array([0, 0, 2])], (0, 1): [array([0, 1, 2]), array([0, 1, 1])], (0, 2): [array([0, 2, 3]), array([0, 2, 2])], (0, 3): [array([0, 3, 3]), array([0, 3, 2]), array([0, 3, 1])], (0, 4): [array([0, 4, 1]), array([0, 4, 3]), array([0, 4, 2])], (1, 0): [array([1, 0, 2])], (1, 1): [array([1, 1, 1])], (1, 2): [array([1, 2, 2]), array([1, 2, 1])], (1, 3): [array([1, 3, 2]), array([1, 3, 3])], (1, 4): [array([1, 4, 2])], (2, 0): [array([2, 0, 3]), array([2, 0, 2])], (2, 1): [array([2, 1, 2]), array([2, 1, 1]), array([2, 1, 3])], (2, 2): [array([2, 2, 2])], (2, 3): [array([2, 3, 2])], (2, 4): [array([2, 4, 2]), array([2, 4, 3])], (3, 0): [array([3, 0, 3]), array([3, 0, 2]), array([3, 0, 1])], (3, 1): [array([3, 1, 2]), array([3, 1, 3])], (3, 2): [array([3, 2, 2])], (3, 3): [array([3, 3, 2]), array([3, 3, 3])], (3, 4): [array([3, 4, 3]), array([3, 4, 2])], (4, 0): [array([4, 0, 1]), array([4, 0, 3]), array([4, 0, 2])], (4, 1)

In [2]:
import networkx as nx
from types_definition import * 
from vector import Vector
from rotorconfig import RotorConfig
from rotorgraph import RotorGraph, display_path, all_config_from_recurrent, display_grid
from particleconfig import ParticleConfig
from matrices import Matrix
from arcsum import ArcSum
from arcmonic import Arcmonic
import numpy as np
from smithnormalform import matrix, snfproblem, z
from otherfunctions import *
import random

In [3]:
import random

m=4
n=6
x=8
y=12


rotor_graph = RotorGraph.simple_path(n,y,x)


In [4]:

L= rotor_graph.laplacian_matrix()
rL=rotor_graph.reduced_laplacian_matrix()
print(L, "\n\n", rL)


prob = L.snf_problem()

#print(sinks)
MatrixT = Matrix(prob.T)
MatrixT = MatrixT.to_numpy()

MatrixJ = Matrix(prob.J)
MatrixJ = MatrixJ.to_numpy()

print(MatrixJ)
print(MatrixT)




[0 0 0 0 0 0 0 0]
[-12 20 -8 0 0 0 0 0]
[0 -12 20 -8 0 0 0 0]
[0 0 -12 20 -8 0 0 0]
[0 0 0 -12 20 -8 0 0]
[0 0 0 0 -12 20 -8 0]
[0 0 0 0 0 -12 20 -8]
[0 0 0 0 0 0 0 0]
 

 [20 -8 0 0 0 0]
[-12 20 -8 0 0 0]
[0 -12 20 -8 0 0]
[0 0 -12 20 -8 0]
[0 0 0 -12 20 -8]
[0 0 0 0 -12 20]

[[4 0 0 0 0 0 0 0]
 [0 4 0 0 0 0 0 0]
 [0 0 4 0 0 0 0 0]
 [0 0 0 4 0 0 0 0]
 [0 0 0 0 4 0 0 0]
 [0 0 0 0 0 4 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[   -9   -32  -105  -332 -1029    -2  2059 -2058]
 [   -7   -28   -97  -316  -997    -1  1995 -1994]
 [   -4   -22   -85  -292  -949     0  1899 -1898]
 [    0   -13   -67  -256  -877     0  1755 -1754]
 [    0     0   -40  -202  -769     0  1539 -1538]
 [    0     0     0  -121  -607     0  1215 -1214]
 [    0     0     0     0  -364     0   729  -728]
 [    0     0     0     0     0     0     0     1]]


In [10]:
sinks={6}
rg=rotor_graph.remove_sink_out_edges(sinks)
L= rg.laplacian_matrix()
rL=rg.reduced_laplacian_matrix()
print(L, "\n\n", rL)


prob = L.snf_problem()

#print(sinks)
MatrixT = Matrix(prob.T)
MatrixT = MatrixT.to_numpy()

MatrixJ = Matrix(prob.J)
MatrixJ = MatrixJ.to_numpy()

print(MatrixJ)
print(MatrixT)




[0 0 0 0 0 0 0 0]
[-12 20 -8 0 0 0 0 0]
[0 -12 20 -8 0 0 0 0]
[0 0 -12 20 -8 0 0 0]
[0 0 0 -12 20 -8 0 0]
[0 0 0 0 -12 20 -8 0]
[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]
 

 [20 -8 0 0 0]
[-12 20 -8 0 0]
[0 -12 20 -8 0]
[0 0 -12 20 -8]
[0 0 0 -12 20]

[[4 0 0 0 0 0 0 0]
 [0 4 0 0 0 0 0 0]
 [0 0 4 0 0 0 0 0]
 [0 0 0 4 0 0 0 0]
 [0 0 0 0 4 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[  -9  -32 -105 -332   -2 -665 -664    0]
 [  -7  -28  -97 -316   -1 -633 -632    0]
 [  -4  -22  -85 -292    0 -585 -584    0]
 [   0  -13  -67 -256    0 -513 -512    0]
 [   0    0  -40 -202    0 -405 -404    0]
 [   0    0    0 -121    0 -243 -242    0]
 [   0    0    0    0    0    0    1    0]
 [   0    0    0    0    0    0    0    1]]


In [8]:
g= RotorGraph.random_graph(7,10)

print(g.laplacian_matrix())

[1 -1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 2 -1 0 0 -1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 -1 0 0 0 0 0 0]
[0 0 0 0 0 1 -1 0 0 0 0 0]
[-1 0 0 0 0 -1 4 -1 0 0 -1 0]
[0 0 -1 0 0 0 0 2 -1 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 -1 0 0 0 0 0 0 2 -1 0]
[0 0 0 0 0 -1 0 0 0 0 3 -2]
[0 0 0 0 0 0 0 0 0 0 0 0]

