In [9]:
import networkx as nx
from types_definition import * 
import vector
from vector import Vector
from rotorconfig import RotorConfig
from rotorgraph import *
from particleconfig import ParticleConfig
from matrices import Matrix
from arcsum import ArcSum
import numpy as np
from smithnormalform import matrix, snfproblem, z
from otherfunctions import *
import random

import matplotlib.pyplot as plt




In [10]:
#Creation du graph complet avec puits et obtention des Laplaciens
sinks=None
n=5
sinks = {0,n-1}
#sinks = {0}
rg = RotorGraph.complete_graph_with_sink(n, sinks)
rotor_graph = rg.remove_sink_out_edges(sinks)


L= rotor_graph.laplacian_matrix()
rL=rotor_graph.reduced_laplacian_matrix()
#print(L, "\n\n", rL)

#SNF du Laplacien
prob = rL.snf_problem()

print(L)

print(sinks)
MatrixT = Matrix(prob.T)
MatrixT = MatrixT.to_numpy()

MatrixJ = Matrix(prob.J)
MatrixJ = MatrixJ.to_numpy()

print(MatrixJ)
print(MatrixT)

[0 0 0 0 0]
[-1 4 -1 -1 -1]
[-1 -1 4 -1 -1]
[-1 -1 -1 4 -1]
[0 0 0 0 0]

{0, 4}
[[ 1  0  0]
 [ 0  5  0]
 [ 0  0 10]]
[[  1   7 -11]
 [  0   2  -3]
 [  0   1  -1]]


In [11]:
#Creation du graph complet avec puits et obtention des Laplaciens
sinks=None
n=5
rotor_graph = complete_graph_with_sink_con(n)



L= rotor_graph.laplacian_matrix()
rL=rotor_graph.reduced_laplacian_matrix()
#print(L, "\n\n", rL)

#print(L)

prob = L.snf_problem()

#print(sinks)

MatrixT = Matrix(prob.T)
MatrixT = MatrixT.to_numpy()

MatrixJ = Matrix(prob.J)
MatrixJ = MatrixJ.to_numpy()

print(MatrixJ)
print(MatrixT)

NameError: name 'complete_graph_with_sink_con' is not defined

In [12]:
#SNF du Laplacien
prob = L.snf_problem()

print(sinks)
MatrixT = Matrix(prob.T)
MatrixT = MatrixT.to_numpy()

MatrixJ = Matrix(prob.J)
MatrixJ = MatrixJ.to_numpy()

print(MatrixJ)
print(MatrixT)

None
[[1 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[-1  3  4  2 -1]
 [ 0  1  1  1  0]
 [ 0  1  0  1  0]
 [ 0  0  0  1  0]
 [ 0  0  0  0  1]]


In [ ]:
#n=5

rho = RotorConfig(rotor_graph)

harmonic_functions= [(0,[4,3,2,1,0])]#,(0,[0,1,2,3,4]),(0,[2,1,1,1,0])]

harmonic_functions= [(5,[5,1,2,2,0]),(10,[10,1,3,9,0])]

arcmonicfonc,orders= armonic_from_harmonic(rotor_graph, rho, harmonic_functions)

#print(arcmonicfonc)

arcmonicnode=arcmonic_per_node(arcmonicfonc)

for i in arcmonicnode.keys():
    print("V"+str(i)+" =", arcmonicnode[i])

V1 = [array([0, 0]), array([4, 9]), array([0, 1]), array([1, 9])]
V2 = [array([0, 0]), array([3, 7]), array([2, 5]), array([2, 1])]
V3 = [array([0, 0]), array([3, 1]), array([2, 3]), array([2, 7])]
V4 = [array([0, 0])]


V1 = [array([0, 0]), array([4, 1]), array([0, 9]), array([1, 9])]
V2 = [array([0, 0]), array([3, 3]), array([2, 5]), array([2, 7])]
V3 = [array([0, 0]), array([3, 1]), array([2, 1]), array([2, 9])]
[(5,[0,1,2,2,0]),(10,[0,9,7,9,0])]

In [ ]:
#Creation du graph complet avec puits et obtention des Laplaciens
sinks=None
n=8
rotor_graph = complete_graph_with_sink_con(n)



L= rotor_graph.laplacian_matrix()
rL=rotor_graph.reduced_laplacian_matrix()
#print(L, "\n\n", rL)

#print(L)

prob = L.snf_problem()

#print(sinks)

MatrixT = Matrix(prob.T)
MatrixT = MatrixT.to_numpy()

MatrixJ = Matrix(prob.J)
MatrixJ = MatrixJ.to_numpy()

print(MatrixJ)
print(MatrixT)

[[ 1  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0]
 [ 0  0  0  8  0  0  0  0]
 [ 0  0  0  0  8  0  0  0]
 [ 0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0 16  0]
 [ 0  0  0  0  0  0  0  0]]
[[ -1   1   0   0   0   0   0   1]
 [  1   0  -1   5  -1  10 -17   1]
 [  0   0   0   1   0   2  -3   1]
 [  0   0   1   1   0   1  -1   1]
 [  0   0   0   1   0   1  -1   1]
 [  0   0   0   0   1   1  -1   1]
 [  0   0   0   0   0   1  -1   1]
 [  0   0   0   0   0   0   0   1]]


In [ ]:
rho = RotorConfig(rotor_graph)

harmonic_functions= [(0,[4,3,2,1,0])]#,(0,[0,1,2,3,4]),(0,[2,1,1,1,0])]



harmonic_functions= [(8,[0, 0, 0, 0, 1, 0, -1, 0]),
                     (8,[0, 0, 0, 1, 1, 1, 5, 0]),
                     (8,[0, 0, 1, 0, 0, 0, -1, 0]),
                     (8,[0, 1, 1, 1, 1, 2, 10, 0]),
                    (16,[0,-1,-1,-1,-1,-3,-17, 0])]

arcmonicfonc,orders= armonic_from_harmonic(rotor_graph, rho, harmonic_functions)

#print(arcmonicfonc)

arcmonicnode=arcmonic_per_node(arcmonicfonc)

for i in arcmonicnode.keys():
    print("V"+str(i)+" =", arcmonicnode[i])

V1 = [array([0, 0, 0, 0, 0]), array([0, 0, 0, 7, 1]), array([0, 0, 1, 7, 1]), array([0, 1, 1, 7, 1]), array([1, 2, 1, 7, 1]), array([ 1,  3,  1,  0, 15]), array([ 0,  0,  0,  1, 15])]
V2 = [array([0, 0, 0, 0, 0]), array([0, 0, 7, 7, 1]), array([0, 0, 6, 7, 1]), array([0, 1, 5, 7, 1]), array([1, 2, 4, 7, 1]), array([ 1,  3,  3,  0, 15]), array([ 0,  0,  1,  1, 15])]
V3 = [array([0, 0, 0, 0, 0]), array([0, 7, 0, 7, 1]), array([0, 6, 0, 7, 1]), array([0, 5, 1, 7, 1]), array([1, 5, 1, 7, 1]), array([ 1,  5,  1,  0, 15]), array([ 0,  1,  0,  1, 15])]
V4 = [array([0, 0, 0, 0, 0]), array([7, 7, 0, 7, 1]), array([6, 6, 0, 7, 1]), array([5, 5, 1, 7, 1]), array([4, 5, 1, 7, 1]), array([ 3,  5,  1,  0, 15]), array([ 1,  1,  0,  1, 15])]
V5 = [array([0, 0, 0, 0, 0]), array([0, 7, 0, 6, 3]), array([0, 6, 0, 5, 5]), array([0, 5, 1, 4, 7]), array([0, 5, 1, 3, 9]), array([ 1,  5,  1,  2, 11]), array([ 0,  1,  0,  2, 13])]
V6 = [array([0, 0, 0, 0, 0]), array([1, 3, 1, 6, 1]), array([2, 6, 2, 5, 1]), ar

In [ ]:
#complete graph on 5 vertices with one sinks: 0

from itertools import product
import numpy as np

def product_sums(*listes):

    combinaisons = product(*listes)
    resultats = [sum(combinaison) for combinaison in combinaisons]
    
    return resultats




V1 = [np.array([0, 0]), np.array([4, 1]), np.array([0, 9]), np.array([1, 9])]
V2 = [np.array([0, 0]), np.array([3, 3]), np.array([2, 5]), np.array([2, 7])]
V3 = [np.array([0, 0]), np.array([3, 1]), np.array([2, 1]), np.array([2, 9])]
V4 = [np.array([0, 0])]


n=5
orders= [5, 10]

resultats = product_sums(V1,V2,V3)


ensemble_unique = set(map(tuple, resultats))
pav = [np.array(x) for x in ensemble_unique]
matrice=np.stack(pav)

print(len(matrice))

#print(len(pav))





matrice2 = []
for element in matrice:
     matrice2.append([element[i]%orders[i] for i in range(len(element))])


matrice2 = np.array(matrice2)
matrice = np.unique(matrice2, axis=0)
print(len(matrice))


for element in matrice:
     print(element)


# #matrice= ensemble des valeurs arcmonique modulo l'ordre



# ######################## Juste pour tester que toutes les valeur sont bien prises pour les valeurs 
# #arcmoniques allant de 1 jusqu'à n-3
# matrice3 = []
# for element in matrice2:
#      matrice3.append([element[i] for i in range(len(element)-1)])

# matrice3 = np.array(matrice3)
# matrice3 = np.unique(matrice3, axis=0)
# print(len(matrice3))
# print("matrice3\n",matrice3)

# # ###matrice3 regroupe les valeurs acrmonique sans prendre en compte la composante  en 0
# # ###qui compte le nombre d'arcs ne pointant par vers le sommet 0 et la valeur arcmonique en n-2 ajouter.
# # ###########################



# dico = dict()
# for element in matrice2:
#     np_array_recherche = tuple(element[:-1])  # Convertir la liste en tuple
#     if np_array_recherche not in dico.keys():
#         dico[np_array_recherche] = []
#     dico[np_array_recherche].append(element)

# print(len(dico))

# #print(dico)

# dico2= dict()





# # for cle in dico.keys():
# #     print (dico[cle])

# for element in matrice3:
#     cle = tuple(element[:]) 
#     pos= [ dico[cle][i] for i in range(len(dico[cle]))]
#     #print(cle,":",sorted(pos) )
#     dico2[cle] = pos



# #print(dico2)

# for cle in dico2.keys():
#     print(cle, ":", dico2[cle])



# # def regrouper_par_valeur(dictionnaire):
# #     regroupement = {}
# #     for cle, valeur in dictionnaire.items():
# #         if valeur not in regroupement:
# #             regroupement[valeur] = [cle]
# #         else:
# #             regroupement[valeur].append(cle)
# #     return regroupement



# # regroupement = regrouper_par_valeur(dico2)

# # for el in regroupement.keys():
# #     print(el,regroupement[el])


# # for cle in regroupement.keys():
# #     print(cle, len(regroupement[cle]))
# #     for truc in regroupement[cle]:
# #         truc = list(truc)
# #         print(sum(truc)%n, end=" ")
    

# #     print()


60
50
[0 0]
[0 1]
[0 2]
[0 3]
[0 4]
[0 5]
[0 6]
[0 7]
[0 8]
[0 9]
[1 0]
[1 1]
[1 2]
[1 3]
[1 4]
[1 5]
[1 6]
[1 7]
[1 8]
[1 9]
[2 0]
[2 1]
[2 2]
[2 3]
[2 4]
[2 5]
[2 6]
[2 7]
[2 8]
[2 9]
[3 0]
[3 1]
[3 2]
[3 3]
[3 4]
[3 5]
[3 6]
[3 7]
[3 8]
[3 9]
[4 0]
[4 1]
[4 2]
[4 3]
[4 4]
[4 5]
[4 6]
[4 7]
[4 8]
[4 9]


In [13]:
n=4
sinks = {0,n-1}
#sinks = {0}


rg= RotorGraph.complete_graph_with_sink(n, sinks)
rotor_graph = rg.remove_sink_out_edges(sinks)

print(rotor_graph.spanning_vector())
print(rotor_graph.edges())
print(rotor_graph.cycle_push_matrix_dict())
#print(rotor_graph.cycle_push_matrix())


MatrixCP = Matrix(rotor_graph.cycle_push_matrix())

MatrixCP = MatrixCP.to_numpy()
print(MatrixCP)

{(1, 0, 0): 1, (1, 3, 0): 1, (2, 0, 0): 1}
[(1, 0), (1, 2), (1, 3), (2, 0), (2, 1), (2, 3)]
{(1, 2, 0): {(1, 0, 0): -1, (1, 2, 0): 2, (2, 1, 0): -1, (1, 3, 0): -1, (2, 0, 0): 1}, (2, 1, 0): {(1, 0, 0): -1, (1, 2, 0): 1, (2, 1, 0): -2, (2, 0, 0): 1, (2, 3, 0): 1}, (2, 3, 0): {(1, 2, 0): 1, (2, 1, 0): -1, (1, 0, 0): -2, (2, 0, 0): 2, (1, 3, 0): 1, (2, 3, 0): -1}}
[[-1  2 -1  1 -1  0]
 [-1  1  0  1 -2  1]
 [-2  1  1  2 -1 -1]]


{(1, 0, 0): 1, (1, 3, 0): 1, (2, 0, 0): 1}
[(1, 0), (1, 2), (1, 3), (2, 0), (2, 1), (2, 3)]

{
(1, 2, 0): {(1, 0, 0): -1, (1, 2, 0): 2, (2, 1, 0): -1, (1, 3, 0): -1, (2, 0, 0): 1}, 
(2, 1, 0): {(1, 0, 0): -1, (1, 2, 0): 1, (2, 1, 0): -2, (2, 0, 0): 1, (2, 3, 0): 1}, 
(2, 3, 0): {(1, 2, 0): 1, (2, 1, 0): -1, (1, 0, 0): -2, (2, 0, 0): 2, (1, 3, 0): 1, (2, 3, 0): -1}
}

[(1, 0), (1, 2), (1, 3), (2, 0), (2, 1), (2, 3)]
[[-1  2 -1  1 -1  0]
 [-1  1  0  1 -2  1]
 [-2  1  1  2 -1 -1]]

In [14]:
[(1, 0), (1, 2), (1, 3), (2, 0), (2, 1), (2, 3)]
v= np.array([0,0,1,0,0,1])


v1= np.array([-1,  2, -1,  1, -1,  0])
v2= np.array([-1,  1,  0,  1, -2,  1])
v3= np.array([-2,  1,  1,  2, -1, -1])



c1= random.randint(-2,2)
c3= random.randint(-1,1)
c2= random.randint(-3,3)
v = v+ c1*v1 + c2*v2 + c3*v3

#


In [ ]:
print(v,c1,c2,c3)

[ 2 -3  2 -2  3  0] -1 -1 0


In [ ]:
print( c1*v1 + c2*v2 + c3*v3)


[-5  2  3  5 -5  0]


In [ ]:
v= np.array([ 7, -7,  1, -7,  2,  6])
v+=7*v1 

print(v1-v2)



[ 0  1 -1  0  1 -1]


In [ ]:
v+= -3*v2
v

array([ 3,  4, -6, -3,  1,  3])

v1= np.array([-1,  2, -1,  1, -1,  0])
v2= np.array([-1,  1,  0,  1, -2,  1])
v3= np.array([-2,  1,  1,  2, -1, -1])

{(1, 0, 0): 1, (1, 4, 0): 1, (2, 0, 0): 1, (3, 0, 0): 1}

{(1, 2, 0): {(1, 0, 0): -1, (1, 2, 0): 2, (2, 1, 0): -1, (1, 3, 0): -1, (2, 0, 0): 1}, 
(1, 3, 0): {(1, 0, 0): -1, (3, 0, 0): 1, (1, 2, 0): 1, (1, 3, 0): 1, (3, 1, 0): -1, (1, 4, 0): -1}, 
(2, 1, 0): {(1, 0, 0): -1, (1, 2, 0): 1, (2, 1, 0): -2, (2, 0, 0): 1, (2, 3, 0): 1}, 
(2, 3, 0): {(3, 0, 0): -1, (2, 4, 0): 1, (2, 0, 0): 1, (2, 1, 0): -1, (3, 1, 0): 1, (2, 3, 0): -1}, 
(2, 4, 0): {(1, 2, 0): 1, (2, 1, 0): -1, (1, 4, 0): 1, (1, 0, 0): -2, (2, 4, 0): -1, (2, 0, 0): 2}, 
(3, 1, 0): {(1, 0, 0): -1, (1, 2, 0): 1, (3, 0, 0): 1, (3, 1, 0): -2, (3, 2, 0): 1}, 
(3, 2, 0): {(3, 0, 0): -1, (3, 4, 0): -1, (2, 0, 0): 1, (2, 1, 0): -1, (3, 1, 0): 1, (3, 2, 0): 1}, 
(3, 4, 0): {(3, 4, 0): -1, (1, 2, 0): 1, (3, 0, 0): 2, (3, 1, 0): -1, (1, 4, 0): 1, (1, 0, 0): -2}}


[(1, 0), (1, 2), (1, 3), (1, 4), (2, 0), (2, 1), (2, 3), (2, 4), (3, 0), (3, 1), (3, 2), (3, 4)]

[-1  2 -1  0  1 -1  0  0  0  0  0  0]
[-1  1  1 -1  0  0  0  0  1 -1  0  0]
[-1  1  0  0  1 -2  1  0  0  0  0  0]
[ 0  0  0  0  1 -1 -1  1 -1  1  0  0]
[-2  1  0  1  2 -1  0 -1  0  0  0  0]
[-1  1  0  0  0  0  0  0  1 -2  1  0]
[ 0  0  0  0  1 -1  0  0 -1  1  1 -1]
[-2  1  0  1  0  0  0  0  2 -1  0 -1]




In [ ]:
#Générer une config de rotor au hazard
rho = RotorConfig(rotor_graph)
for i in range(1,n-1):
    eh= random.randint(0, len(rotor_graph.rotor_order[i])-1)
    rho[i]= rotor_graph.rotor_order[i][eh]

#Transformer la config de rotor en somme d'arc
somme_arc = ArcSum(rho)

print(somme_arc)

#Ajouter à la somme les éléments router sur le puits 0: 
for i in range(1,n-1):
    edge = (i, 0, 0)
    nb = random.randint(0,n)
    for _ in range(nb):
        somme_arc = somme_arc + rotor_graph.turn(edge) - edge


#Ajouter à la somme les éléments router sur le puits n-1: 
for i in range(1,n-1):
    edge = (i, n-1, 0)
    nb = random.randint(0,n)
    for _ in range(nb):
        somme_arc = somme_arc + rotor_graph.turn(edge) - edge

#somme_arc = config de rotor + config obtenu apres tirage directe dans les puits 0 et n-1
arc_sum = ArcSum(somme_arc)

print(arc_sum)

print("\nCycle",arc_sum.find_cycle_dp())
print("\nCycle",arc_sum.find_cycle_dn())


rotorconfig_in_class_by_stabilization(rotor_graph,arc_sum)

{(1, 3, 0): 1, (2, 3, 0): 1}
{(1, 3, 0): -1, (2, 3, 0): -1, (2, 1, 0): 3, (2, 0, 0): -1, (1, 0, 0): 2}

Cycle None

Cycle None


{1: (1, 0, 0), 2: (2, 3, 0)}

In [ ]:
print(arc_sum)
print("\nCycle",arc_sum.find_cycle())

b={(1, 3, 0): -1, (2, 3, 0): -1, (2, 1, 0): 3, (2, 0, 0): -1, (1, 0, 0): 2}

{(1, 3, 0): -1, (2, 3, 0): -1, (2, 1, 0): 3, (2, 0, 0): -1, (1, 0, 0): 2}

Cycle {(1, 3, 0): 1, (2, 3, 0): -1, (2, 1, 0): 1}


In [ ]:
import pulp

# Définir le problème
prob = pulp.LpProblem("Problème d'optimisation entière", pulp.LpMinimize)

# Définir les variables
x = pulp.LpVariable.dicts("x", range(3), lowBound=None, cat=pulp.LpInteger)

# Définir les contraintes
A = [[-1, -1, -2],
     [ 2,  1,  1],
     [-1,  0,  1],
     [ 1,  1,  2],
     [-1, -2, -1],
     [ 0,  1, -1]]
b = [-5,  2,  3,  5, -5,  0]

for i, row in enumerate(A):
    prob += pulp.lpSum(row[j] * x[j] for j in range(3)) <= b[i]

# Résoudre le problème
prob.solve()

print("Statut de la solution:", pulp.LpStatus[prob.status])
print("Solution optimale:")
for v in prob.variables():
    if v.varValue is not None:
        print(v.name, "=", int(v.varValue))
    else:
        print(v.name, "n'a pas de valeur attribuée")


Welcome to the CBC MILP Solver 
Version: 2.10.3 
Build Date: Dec 15 2019 

command line - /home/krex/.local/lib/python3.10/site-packages/pulp/solverdir/cbc/linux/64/cbc /tmp/d6b88654c5114ca391ee61e258bbbff8-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/d6b88654c5114ca391ee61e258bbbff8-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 11 COLUMNS
At line 35 RHS
At line 42 BOUNDS
At line 47 ENDATA
Problem MODEL has 6 rows, 4 columns and 16 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 0 - 0.00 seconds
Cgl0003I 0 fixed, 6 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 2 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0004I processed model has 6 rows, 3 columns (3 integer (0 of which binary)) and 16 elements
Cbc0012I Integer solution of 0 found by DiveCoefficient after 0 iterations and 0 nodes (0.00 seconds)
Cbc0001I Search

In [ ]:
import pulp

# Définir le problème
prob = pulp.LpProblem("Problème d'optimisation entière", pulp.LpMinimize)

# Définir les variables
x = pulp.LpVariable.dicts("x", range(3), lowBound=None, cat=pulp.LpInteger)

# Définir les contraintes
A = [[-1, -1, -2],
     [ 2,  1,  1],
     [-1,  0,  1],
     [ 1,  1,  2],
     [-1, -2, -1],
     [ 0,  1, -1]]
#b = [-3, -1,  5,  3, -2,  0]
#b = [0,   1,  0, -1,  2,  0]
b = [0,   1,  0,  1,  1,  -1]

b = [2,   0, -1,   0,  1,  0]

for i, row in enumerate(A):
    prob += pulp.lpSum(row[j] * x[j] for j in range(3)) <= b[i]

# Résoudre le problème
prob.solve()

print("Statut de la solution:", pulp.LpStatus[prob.status])
print("Solution optimale:")

sol = []
for v in prob.variables():
    if v.varValue is not None:
        print(v.name, "=", int(v.varValue))
        sol.append((v.varValue))
    #else:
        #print(v.name, "n'a pas de valeur attribuée")

print(sol)


rho= np.array(b)- np.dot( np.array(A), np.array(sol))
print(rho)

#print( np.linalg.det(np.array(A)))

Welcome to the CBC MILP Solver 
Version: 2.10.3 
Build Date: Dec 15 2019 

command line - /home/krex/.local/lib/python3.10/site-packages/pulp/solverdir/cbc/linux/64/cbc /tmp/02e4579dbe19486181811d344addad58-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/02e4579dbe19486181811d344addad58-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 11 COLUMNS
At line 35 RHS
At line 42 BOUNDS
At line 47 ENDATA
Problem MODEL has 6 rows, 4 columns and 16 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 0 - 0.00 seconds
Cgl0003I 0 fixed, 6 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0004I processed model has 6 rows, 3 columns (3 integer (0 of which binary)) and 16 elements
Cbc0031I 1 added rows had average density of 2
Cbc0013I At root node, 2 cuts changed objective from 0 to 0 in 1 passes
Cbc0014I Cut generator 0 (Probing) - 0 row cuts average 0.0 elements, 0 c

/home/krex/.local/lib/python3.10/site-packages/pulp/pulp.py:1316: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")


In [ ]:
[(1, 0), (1, 2), (1, 3), (2, 0), (2, 1), (2, 3)]
v= np.array([0,1,0,0,1,0])


v1= np.array([-1,  2, -1,  1, -1,  0])
v2= np.array([-1,  1,  0,  1, -2,  1])
v3= np.array([-2,  1,  1,  2, -1, -1])



c1= random.randint(-5,5)
c3= random.randint(-5,5)
c2= random.randint(-5,5)
v = v+ c1*v1 + c2*v2 + c3*v3

#


NameError: name 'np' is not defined

In [ ]:
print(v,c1,c2,c3)

[-3 -1  5  3 -2  0] -3 2 2


In [ ]:
print(5*v1 + v2 + v3)
print(c1*v1 + c2*v2 + c3*v3)

[-8 12 -4  8 -8  0]
[-8 11 -3  8 -9  1]


In [ ]:
import cvxpy as cp
import numpy as np

# Définir les variables
n = 3  # Nombre de variables
x = cp.Variable(n)


A = np.array([[-1, -1, -2],
     [ 2,  1,  1],
     [-1,  0,  1],
     [ 1,  1,  2],
     [-1, -2, -1],
     [ 0,  1, -1]])
#b = [-3, -1,  5,  3, -2,  0]
#b = [0,   1,  0, -1,  2,  0]
b = np.array([0,   1,  0,  1,  1,  -1])

#b = np.array([0,   1,  0,  -1,  2,  0])
constraints = [A @ x <= b]

# Définir la fonction objectif (nulle car nous cherchons à résoudre uniquement les contraintes)
objective = cp.Minimize(0)

# Définir le problème d'optimisation
problem = cp.Problem(objective, constraints)

# Résoudre le problème avec le solveur ECOS
problem.solve(solver=cp.ECOS)

# Afficher la solution
print("Solution du système d'inéquations:")
print("x =", x.value)

sol= x.value
rho= np.array(b)- np.dot( np.array(A), np.array(sol))

print((rho))


Solution du système d'inéquations:
x = [ 0.49319407 -0.74319471  0.37500089]
[0.50000114 0.38180568 0.11819318 0.49999886 0.38180554 0.1181956 ]


In [ ]:
c = np.array([[1,   0,  0,  1,  0,  0],
              [1,   0,  0,  0,  1,  0],
              [1,   0,  0,  0,  0,  1],
              [0,   1,  0,  1,  0,  0],
              [0,   1,  0,  0,  1,  0],
              [0,   1,  0,  0,  0,  1],
              [0,   0,  1,  1,  0,  0],
              [0,   0,  1,  0,  1,  0],
              [0,   0,  1,  0,  0,  1]])


p = np.array([[-1,   1,  0,  0,  0,  0],
                [1,   0,  -1,  0,  0,  0],
                [0,  0,  0, -1,   1,  0],
                [0,  0,  0, 1,   0,  -1]])


import cvxpy as cp
import numpy as np

# Définir les variables
n = 3  # Nombre de variables
x = cp.Variable(n)


A = np.array([[-1, -1, -2],
     [ 2,  1,  1],
     [-1,  0,  1],
     [ 1,  1,  2],
     [-1, -2, -1],
     [ 0,  1, -1]])


for i in c:
    for j in p:
        b= i+j
        #if any(b<0): 
            
        constraints = [A @ x <= b]
        objective = cp.Minimize(0)
        problem = cp.Problem(objective, constraints)
        problem.solve(solver=cp.ECOS)

        # Afficher la solution
        print(i, " + ", j, " ", x.value)
            

            
             

[1 0 0 1 0 0]  +  [-1  1  0  0  0  0]   [0.24319186 0.00680858 0.1250002 ]
[1 0 0 1 0 0]  +  [ 1  0 -1  0  0  0]   None
[1 0 0 1 0 0]  +  [ 0  0  0 -1  1  0]   [-0.00680858 -0.24319186 -0.1250002 ]
[1 0 0 1 0 0]  +  [ 0  0  0  1  0 -1]   None
[1 0 0 0 1 0]  +  [-1  1  0  0  0  0]   [ 3.32424142e-01 -3.32424142e-01  2.12850795e-11]
[1 0 0 0 1 0]  +  [ 1  0 -1  0  0  0]   [ 0.5 -0.5 -0.5]
[1 0 0 0 1 0]  +  [ 0  0  0 -1  1  0]   [ 0.0824237  -0.58242396 -0.24999987]
[1 0 0 0 1 0]  +  [ 0  0  0  1  0 -1]   [ 0.25 -0.75  0.25]
[1 0 0 0 0 1]  +  [-1  1  0  0  0  0]   [ 0.08242251  0.417578   -0.25000026]
[1 0 0 0 0 1]  +  [ 1  0 -1  0  0  0]   [ 0.25  0.25 -0.75]
[1 0 0 0 0 1]  +  [ 0  0  0 -1  1  0]   [-0.16757759  0.16757791 -0.50000016]
[1 0 0 0 0 1]  +  [ 0  0  0  1  0 -1]   [ 4.1205036e-10 -4.1205036e-10  1.6941336e-24]
[0 1 0 1 0 0]  +  [-1  1  0  0  0  0]   [ 0.58242395 -0.0824237   0.24999987]
[0 1 0 1 0 0]  +  [ 1  0 -1  0  0  0]   [ 0.75 -0.25 -0.25]
[0 1 0 1 0 0]  +  [ 0  0  0 -1 

In [ ]:
a= (5**5)%85
a


65